### ISSUE TITLE
Have to reinstall after reboot

### ISSUE THREAD

**Issue by curtturtle** [AndrewBabbitt97/AuraConnect#10]
I am trying to sync an Asus mobo with razer synapse. After I install you software it works, however after a reboot it no longer syncs with synapse and reverts the leds to Asus' preferences and I need to reinstall asus connect to get them to sync. Synapse can see the asus connect but wont sync. Please let me know if I can give any more info.

**Comment by MChirodea** [comment]
Maybe your asus LightingControl service doesn’ t start up or hangs, try starting/restarting the service from task manager

**Comment by curtturtle** [comment]
So it looks to have been caused by Amoury Crate (New Asus Sync) blocking it. I uninstalled Armoury Crate and it looks to be syncing with no problem. Cheers for your work. I am so happy that everything now syncs properly.

**Comment by AndrewBabbitt97** [comment]
I'll be releasing a new version this weekend, I am currently using armory Crate but that may not work for everyone (it's dependent on motherboard AFAIK)

**Comment by AndrewBabbitt97** [comment]
New release is out, please test this new release and let me know how things are in it:

https://github.com/AndrewBabbitt97/AuraConnect/releases/tag/1.0.1

**Comment by curtturtle** [comment]
Awesome I'll test it out this weekend and give you feedback.

**Comment by AndrewBabbitt97** [comment]
Have you tested this?

**Comment by curtturtle** [comment]
Yes. I sent an email but it looks to have bounced back into my spam folder.
Weird. It is all working. Everytime there is a new update for aura, I need
to reinstall your code, but that fixes the problem.

I'll let you know should anything change.

**Comment by AndrewBabbitt97** [comment]
Thanks for letting me know, I could see an update to AURA requiring a reinstall (shouldn't need one, definitely a restart of the service however).

Please feel free to reopen this issue if this comes back.
