### ISSUE TITLE
aura not showing up in synapse, but did it the first time.

### ISSUE THREAD

**Issue by noaher78** [AndrewBabbitt97/AuraConnect#100]
so i installed this once, but after i shut down and opened my pc, the aura symbol in synapse said: unreachable. i tried to reinstall all of it again several times, but it just wont show up. im on a intel pc (10850k), and as stated before i succesfully installed this initially.

**Comment by wiglette** [comment]
Lucky you, I haven't been able to get that far at all. I'm currently on a Ryzen 7 with an ASUS GPU, not sure if you need to have an ASUS Motherboard as well in order for this to properly work. Followed all the steps but I have never managed to get the Aura to show up on Synapse.

**Comment by noaher78** [comment]
Yes i have been fairly lucky, but the fact that I was that close is also really frustrating. Btw I'm sorry to hear that it just wont work for you man, that would really piss me off aswell. If ASUS and Razer could just collab... None of these problems would be relevant anymore!

**Comment by wiglette** [comment]
I've been troubleshooting for days on this, uninstalling, re-installing, making sure everything is configured correctly & nothing. It's the only piece missing to having my system synced up. It's really annoying that ASUS won't collab with Razer, you see other huge players already collaborating with Razer.

**Comment by AndrewBabbitt97** [comment]
Need logs from C:\ProgramData\AuraConnect

Unavailable can indicate many things from AV software to anti cheat software. It's usually something on your PC causing issues with the software.

**Comment by wiglette** [comment]
Thanks Andrew for reaching back out to us

Do you know any particular AVs that may cause this issue?

**Comment by wiglette** [comment]
Hi Andrew, 

Any update on this?

**Comment by AndrewBabbitt97** [comment]
McAfee is the most notorious. I personally run the built in windows AV.

Also sorry if replies are slow right now, it is the holidays after all.

**Comment by noaher78** [comment]
So hi again Andrew. The reason i think it isnt working, is, that my pcs rgb flash, and then turns off until entering windows. But even in windows the motherboards rgb wont sync, so therefore, i considered save erasing my ssd and reinstall windows, since the system was build a few days ago too. Do you think that would be a bad idea? 
(Could it get me into a world of problems, or would it just work, or just change nothing?)
Kind regards - Noah

**Comment by noaher78** [comment]
Hi Andrew. Is there a chance you might take a look at my case above in the nearest future?

If you dont want to or are too busy I understand - just let me know if thats is the case - Noah.

**Comment by AndrewBabbitt97** [comment]
It's the holidays and I have been spending time with family, will have a chance to look at this sometime this upcoming week.

**Comment by AndrewBabbitt97** [comment]
AuraConnect has been archived, please move onto the replacement ChromaControl: https://github.com/ChromaControl/ChromaControl
