### ISSUE TITLE
AuraConnect log files take up 230GB?

### ISSUE THREAD

**Issue by VANIRRA** [AndrewBabbitt97/AuraConnect#102]
So I was just doing my stuff and noticed that Windows turned on disk optimization for some reason, I thought that I had like 250GB still free on my disk. So I went to look for a problem, not my Steam library, not Windows, but somehow over 220GB of log files by AuraConnect and keeps rising. 
![Screenshot_31](https://user-images.githubusercontent.com/29003481/102602814-0aa75800-40f0-11eb-88cf-7fdae9fa0cc8.png)
![Screenshot_32](https://user-images.githubusercontent.com/29003481/102602826-0d09b200-40f0-11eb-9bae-ef62629b9863.png)
![Screenshot_33](https://user-images.githubusercontent.com/29003481/102602836-0f6c0c00-40f0-11eb-8b65-0bbf70995cb9.png)
I don't know what might be the problem, but I noticed that my ligthing on my motherboard stopped working, but I didn't pay much attention to it. Force closing the app from task manager and deleting the log file of course helped, but hope that you could fix the bug.

**Comment by AndrewBabbitt97** [comment]
This would indicate that performance metrics were turned on at some point but never off again.

**Comment by VANIRRA** [comment]
Could you tell me how to turn them off? Because I don't really remember turning them on in the first place.

**Comment by VANIRRA** [comment]
The issue was resolved btw after I reinstalled it and now it doesn't just constantly write information into the dock.
