### ISSUE TITLE
Aura Is unreachable in chroma studio

### ISSUE THREAD

**Issue by speedrunner346** [AndrewBabbitt97/AuraConnect#103]
![image](https://user-images.githubusercontent.com/76505893/102956209-574ab480-449d-11eb-806e-ce8fe9b18914.png)
I had it working maybe 6 months ago and for a while somehow the razer visualizer worked even when it said it was unreachable but now I cant get anything to work. I have tried uninstalling razer synapse and chroma connect along with many pc restarts but nothing helps.
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/5733124/AuraConnect.log)

**Comment by AndrewBabbitt97** [comment]
Need logs from C:\ProgramData\AuraConnect

**Comment by speedrunner346** [comment]
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/5758432/AuraConnect.log)
This is the exact file i sent originally but here it is again.

**Comment by AndrewBabbitt97** [comment]
AuraConnect has been archived, please move onto the replacement ChromaControl: https://github.com/ChromaControl/ChromaControl
