### ISSUE TITLE
No sync when game has special effects

### ISSUE THREAD

**Issue by Jasper1911** [AndrewBabbitt97/AuraConnect#105]
When a game "takes over" chroma; aura connect is not synced like the other razer peripherals, just stays onthe former profile not reacting to for instance a legendary drop in diablo 3,or going all red when starting vermintide. Mouse and keyboard do however.

**Comment by KyleStilkey** [comment]
This was an issue before they pushed out a update. If you have control over your devices with Synapse but a game starts and you are "frozen" on your last color, make sure you are fully updated with Synapse. If it's still happening try disabling any extra Modules and see if one is causing a conflict. Every now and then the Hue one for me causes all my colors to stop working when it comes to game effect but when I remove it, it would work again.

Just some troubleshooting steps to try.

**Comment by AndrewBabbitt97** [comment]
AuraConnect has been archived, please move onto the replacement ChromaControl: https://github.com/ChromaControl/ChromaControl
