### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by Sandpie00** [AndrewBabbitt97/AuraConnect#106]
It just doesn't work. I have Armoury Crate installed and it seems to "overwrite" whatever color I set from Synapse's Chroma Studio. Sometimes it says "Unreachable". Here's the log: [AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/5781478/AuraConnect.log)

**Comment by AndrewBabbitt97** [comment]
AuraConnect has been archived, please move onto the replacement ChromaControl: https://github.com/ChromaControl/ChromaControl
