### ISSUE TITLE
Suffering from Aura CPU costs

### ISSUE THREAD

**Issue by Janluucas** [AndrewBabbitt97/AuraConnect#107]
Razer Synapse is very good optimized, but when you use something else then a static color in Aura it uses up around 10% of the CPU, which is a significant performance loss. I hoped, when i use Razer Synapse I would have its performance, but Aura is running too and consumes my CPU performance.

**Comment by KyleStilkey** [comment]
This is an issue with Asus Aura. It's been a on going issue forever. It's less noticeable on higher end systems but on the average consumer PC it's really noticeable impact.

**Comment by AndrewBabbitt97** [comment]
Yeah, its an Aura call cost. Due to the frequency of COM calls to Aura it has a terrible CPU penalty.
