### ISSUE TITLE
Stutter

### ISSUE THREAD

**Issue by Exreno21** [AndrewBabbitt97/AuraConnect#11]
Hey, I've installed the 1.0.0.1 AuraConnect exe, along with aura 1.07.79. I also have the Cooler Master software for the Wraith Prism, which has worked fine by itself and smoothly syncing with Razer Chroma. After I added AuraConnect and Aura, both the Wraith and motherboard/RAM have very choppy animations and stutter from one color to another, like from red straight to yellow. This only affects the PC components, kb and mouse are smooth. I have restarted my computer but still there. Any suggestions? 

3700x, ROG x570-E.

**Comment by AndrewBabbitt97** [comment]
I'm going to be looking at all of this more this weekend, I'll be releasing a new version. I'll have you test with that.

**Comment by Exreno21** [comment]
That sounds great, thank you for your effort to make this work! I'll try reinstalling all the software, and if no avail, I'll look forward to your new version.

**Comment by AndrewBabbitt97** [comment]
New release is out, please test this new release and let me know how things are in it:

https://github.com/AndrewBabbitt97/AuraConnect/releases/tag/1.0.1

**Comment by Exreno21** [comment]
OMG it works! My cooler is still kind of funky but I don't think it has anything to do with your module. I'm going to have to play around with my Chroma Studio a bit more, but it seems like some lighting presets allow the MB and ram to change like a wave, and on others it just changes statically like one individual light. Anyways, thank you for the help!
