### ISSUE TITLE
AuraSync not appearing in Syanpse 3

### ISSUE THREAD

**Issue by skins007** [AndrewBabbitt97/AuraConnect#110]
Hello,

I have recently installed AuraConnect, however the device has never appeared in synapse. I can see the AuraConnect service is running. I have also tried reinstalling a couple times, with no success. I also do not have any log files appearing in the install directory.

I have tried stopping the service and running the AuraConnect.exe manually, which I get the following output in the console. 

info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Program Files\ASUS\AURACONNECT
info: AuraConnect.Worker[0]
      Initializing Aura Connect...

After which it never moves from this point.

**Comment by sjsn2002** [comment]
Same happened to me

**Comment by AndrewBabbitt97** [comment]
Please check if atkexComSvc.exe is running in the background.

**Comment by skins007** [comment]
Responded in #104 , 

Managed to get atkexComSvc.exe running, however still does not appear in Synapse.

![Uploading image.png…]()

**Comment by skins007** [comment]
Responded in #104 ,

Managed to get atkexComSvc.exe running, however still does not appear in Synapse.

![image](https://user-images.githubusercontent.com/47616334/105023887-6bcd9d00-5a9b-11eb-9413-6b4980c4e03a.png)

**Comment by robocorpse** [comment]
The latest version of Synapse that was installed seems to block AuraConnect. :(

**Comment by nitanmarcel** [comment]
@AndrewBabbitt97 I have this issue too. Is this project dead or there will be an update soon?

**Comment by AndrewBabbitt97** [comment]
There will be no more updates to this. Use [ChromaControl](https://github.com/ChromaControl/ChromaControl/releases/tag/msix-beta).
