### ISSUE TITLE
Lights are stuttering

### ISSUE THREAD

**Issue by Ragunator** [AndrewBabbitt97/AuraConnect#111]
Light are stuttering heavily when transitioning to another colour. It's been happening for a while, had the issue back when I was using Aura, the issue is still happening after I removed all Aura apps and switched to Armoury Crate. Connected RGB devices are an Asus Rog Claymore and the RGB header on a Prime Z270-A motherboard. 

[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/5824932/AuraConnect.log)

**Comment by AndrewBabbitt97** [comment]
Need perf metrics for logs to be useful: https://github.com/AndrewBabbitt97/AuraConnect/blob/master/docs/PerformanceMetrics.md

**Comment by Oc3lott** [comment]
Hi, I have the same problem, here is my log: 

[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/5832693/AuraConnect.log)

**Comment by Ragunator** [comment]
I took some performance metrics, new log is attached.
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/5836069/AuraConnect.log)

**Comment by AndrewBabbitt97** [comment]
Unfortunately It looks like the call that is taking a while is in ASUS's SDK, Its the call to update LEDs.

Seeing as this is not a part of my code, there's nothing I can do on this front.

In terms of recommendations to fix this (In order of most to least recommended) :

1. Reinstall Armory Crate
2. Update all device HALs in Armory Crate
3. Ensure all ASUS driver updates are installed
4. Reinstall windows

If none of this helps, there's not really anything I can do. The problem at that point lies within ASUS's code.
