### ISSUE TITLE
AuraConnect Misordering G.Skill LEDs

### ISSUE THREAD

**Issue by ShortCIrcuit217** [AndrewBabbitt97/AuraConnect#112]
G.Skill Trident Memory is detected but only seems to see 4 of the 5 LEDs and assigns the top LED to the same area as one of the others. All four RAM modules are seen as one device and sync together. Synapse shows 4 LEDs being controlled. AuraSync is able to control them normally, control each stick individually, and see each led.

**Comment by AndrewBabbitt97** [comment]
This is a limitation of Razers lighting SDK, we are only given 4 LEDs worth of color to work with from Synapse.

Looking to potentially add a buffer to store more, but this will be a bit out. Ill need to do some experimentation with this.
