### ISSUE TITLE
Unable to get AuraConnect into Synapse

### ISSUE THREAD

**Issue by GlassWolff** [AndrewBabbitt97/AuraConnect#113]
Had a lot of trouble updating my laptop to function properly from Aura Core to Armoury Crate. It's now up and running well, and so is Synapse. Currently, I have AuraConnect installed, and it's running in services and unblocked from my firewall, but will not show in Synapse.

**Comment by robocorpse** [comment]
Latest version of Synapse appears to break it.

**Comment by AndrewBabbitt97** [comment]
You are on a laptop? If so, it's not supported.

Latest version of Synapse works fine, however there's a very large transition about to happen here sometime this week. I have updated all of the libraries used in this project, created and tested a new installer that's now signed with a code signing cert (antivirus issues shouldn't be a thing anymore), and improved connectivity to Synapse.

I'm currently working on a configuration UI that will allow you to turn on some debugging features as well as get logs easier. I may just roll out a beta before this is done for those interested in testing.

**Comment by GlassWolff** [comment]
Yeah, the laptop seems to be a recurring problem, especially with it's build date while even trying to set up ASUS' own native RGB again. Awesome though, can't wait for the new version (if I'm understanding correctly that it'll have laptop support).

**Comment by AndrewBabbitt97** [comment]
Laptop support is dependent on AURA SDK, so thats outside of my control.

**Comment by mind-overflow** [comment]
I have a desktop and I'm having the same issue. Nothing shows up in Synapse, although:
1. Armoury Crate is installed and recognizes stuff
2. AuraConnect service is running
3. Synapse has Connect enabled

Honestly, I wouldn't be surprised if @robocorpse was right...

**Comment by AndrewBabbitt97** [comment]
Have you previously had it work?

I'm currently on the latest version of Synapse, but I am also using development bits rather than the latest release.

**Comment by robocorpse** [comment]
> Have you previously had it work?
> 
> I'm currently on the latest version of Synapse, but I am also using development bits rather than the latest release.

It was working fine before the latest update of synapse

**Comment by robocorpse** [comment]
So, It's been moved from being an icon on the landing page of synapse... You have to go to Chrome Connect... then in the green bar at the top of the screen you have to select devices.  There you can turn on Chroma Connect and then enable Aura. 


Synapse UI is really bad.

**Comment by robocorpse** [comment]
To update that, it worked when I turned it on after posting, but only for about 30 minutes to 1 hour. After that it the Aura devices went dark completely and I can't turn the LED's on at all, even in Armoury Crate. Turned Chroma Connect on and off, Asus Aura with in in on and off doesn't do anything. 

/shrug

**Comment by robocorpse** [comment]
Now it's back on the main page? 

I've done nothing. But also, now it works until it doesn't... It was spectrum cycling with everything else then it froze at one color, then it went into rainbow mode (I think that's the fail safe)... at that point I can't control it from synapse or aura/armoury crate.

**Comment by mind-overflow** [comment]
<

> Have you previously had it work?
> 
> I'm currently on the latest version of Synapse, but I am also using development bits rather than the latest release.

In my case, it was fine before a Windows fresh install, which happened a few days ago. After reinstalling Windows, Synapse, Armoury Crate, ... I was unable to have it show in Synapse, even after following all your troubleshooting instructions and whatnot.

**Comment by AndrewBabbitt97** [comment]
I'm not accepting any bugs for AuraConnect from now on, please uninstall everything you have (both Aura Connect and Chroma Control) and install the MSIX beta for Chroma Control.

https://github.com/ChromaControl/ChromaControl/releases/tag/msix-beta

If you have an issue with the beta please open an issue on the Chroma Control project.
