### ISSUE TITLE
Does it work with products compatible with Aura Sync? Like example: iCue -> Aura Sync -> Razer Synapse? 

### ISSUE THREAD

**Issue by imadethisaccounttoaskyouthisquestion** [AndrewBabbitt97/AuraConnect#115]
Title says all. I want to get an H100i RGB Platinum SE for my build but I'm worried I won't be able to sync iCue with Synapse via Aura Sync.

**Comment by AndrewBabbitt97** [comment]
You should be looking at [ChromaControl](https://github.com/ChromaControl/ChromaControl) and the new MSIX beta I released in the past week. ChromaControl will be replacing this.

**Comment by imadethisaccounttoaskyouthisquestion** [comment]
You mean ChromaControl has both iCue and Asus Aura? Sick AF!
