### ISSUE TITLE
Does it work with Asus Rog Strix G512LV?

### ISSUE THREAD

**Issue by LouisLoGaming** [AndrewBabbitt97/AuraConnect#116]
I installed your software but nothing shows up in synapse. I have an aluminated keyboard and use armoury crate and aura creator.

Is it posible on my device or not?

Thanks in advance mate

**Comment by AndrewBabbitt97** [comment]
Laptops are not directly supported by me, if yours works cool but if not you're out of luck. This was primarily designed for desktop motherboards + rgb headers. Aura Creator being installed is not supported at all when using any of my projects, it has the potential to interfere with AuraConnect and ChromaControl.

Also this project is about to be archived, use Chroma Control instead: https://github.com/ChromaControl/ChromaControl/releases/tag/msix-beta
