### ISSUE TITLE
Occasionally freezes on a single color while other devices continue

### ISSUE THREAD

**Issue by robocorpse** [AndrewBabbitt97/AuraConnect#117]
So I am using spectrum cycling, and it usually works fine, but occasionally the Aura devices will stop on a certain color and stay there, I can only try to override them off with Amoury Crate. 

XG279Q, GL731GW, amoury crate 3.3.7.0 

Synapse version 3.6.130.11816

I'd like to try maybe terminating the process and restarting it?

**Comment by AndrewBabbitt97** [comment]
Not taking issues for AuraConnect, use the ChromaControl beta: https://github.com/ChromaControl/ChromaControl/releases/tag/msix-beta

This project will be archived sometime soon.
