### ISSUE TITLE
New Asus LC update 02/04/21 causing issues

### ISSUE THREAD

**Issue by Mattomstormy** [AndrewBabbitt97/AuraConnect#118]
new LC update released and once installed sync dies not work and lighting just shuts down until the aura connect driver is uninstalled,  troubleshooting over the next day or so will update if anything comes to light.  Any input would be fantastic.

Cheers

**Comment by AndrewBabbitt97** [comment]
Ensure your BIOS is up to date and use ChromaControl: https://github.com/ChromaControl/ChromaControl/releases/tag/msix-beta

I will not be supporting AuraConnect going forward, the project will be archived. All development efforts will be towards ChromaControl from now on.
