### ISSUE TITLE
RGB not updating untill reboot

### ISSUE THREAD

**Issue by UomoSaiber** [AndrewBabbitt97/AuraConnect#12]
The RGB on my RAM (G.Skill Trident Z) and on my monitor (ASUS ROG STRIX XG248Q) does not update if I change it from razer synapse, but, if I restart my system it will go to what I put it as the last time I changed it.
I was thinking maybe I was doing something wrong and I needed to put aura on some kind of setting, but that doesn0t seem to be the issue.

**Comment by AndrewBabbitt97** [comment]
Please reinstall Synapse and AURA and report back, this sounds like a weird install issue on that side.

Also if you can get me the AuraConnect log files in C:\ProgramData\AuraConnect.

**Comment by UomoSaiber** [comment]
alredy done that, but I have an update, it seems that if aura starts automaticly at boot it doesn't work, but if I open it manually it does

**Comment by AndrewBabbitt97** [comment]
What version of Synapse and Aura are you using?

**Comment by AndrewBabbitt97** [comment]
It may be that something is interfering with the connection between AuraConnect and Synapse, what Antivirus are you using?

**Comment by UomoSaiber** [comment]
The problem seems to have fixed itself a few days ago, but sometimes it comes back, I'm using the latest version of both aura and synapse and I have no antivirus (other than windows defender)

**Comment by UomoSaiber** [comment]
I've also checked if I have any other program that controlles RGB, but I found nothing

**Comment by AndrewBabbitt97** [comment]
This issue is related to synapse, if it doesnt respond right after a install you need to restart your PC for it to work.
