### ISSUE TITLE
AuraConnect not being picked up by Synapse 3.

### ISSUE THREAD

**Issue by w1nterB** [AndrewBabbitt97/AuraConnect#121]
HI Andrew,
I'm a huge fan of AuraConnect as I have been able to use it without any problems with my ASUS ROG components, on my PC.
I also own a ASUS ROG Strix Scar III - GL531GV laptop that I use while im away from my PC.
I have installed the latest release of AuraConnect, I have confirmed that the service is running both with local system log on and the log on as user workaround method.

My Synapse 3 is version/build -3.6.130.11816

This is the version extract from Armory Crate app.

Armory Crate version 3.3.7.0
Item                       Version     
----                       -------     
Armoury Crate UWP App      3.3.7.0     
ROG Live Service           1.1.16.0    
AURA Service (Lighting Service)  3.04.32     
Armoury Crate service      3.3.7       
ASUS Aac_NBDT HAL          2.4.4.0     
ASUS Keyboard HAL          1.01.12     
ASUS MB Peripheral Products  1.0.33      
ASUS Mouse HAL             1.1.0.8     
AacAudioHal                1.3.7.0     
AacDispaly                 1.1.25   

I have a completely new set of installations of all these softwares, and I use Windows Defender as my AV, like yourself. (Even disabled it to check if it was acting up).

The following is my AuraConnect log:

2021-02-15T10:11:07.0198915+11:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Application started. Hosting environment: Production; Content root path: C:\Program Files (x86)\ASUS\AURACONNECT\
2021-02-15T10:11:08.0281712+11:00	INFO	[AuraConnect.Worker]	[Logging]	Initializing Aura Connect...
2021-02-15T10:26:36.6645979+11:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Application is shutting down...
2021-02-15T10:26:42.8336192+11:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Application started. Hosting environment: Production; Content root path: C:\Program Files (x86)\ASUS\AURACONNECT\
2021-02-15T10:26:43.8471712+11:00	INFO	[AuraConnect.Worker]	[Logging]	Initializing Aura Connect...

If you need more info, I shall be posting the performance metrics logs as well.

My issue is: Synapse just doesnt detect Aura Sync, however, it worked fine on my PC. I dont have access to my tower anymore, I still have access to rest of my Razer peripherals (Blackwidow 2019, Viper Ultimate, Goliathus). Because the laptop's pretty much covered by RGB lighting, I wanted to have all of these in sync.

Anything I can do to fix the issue?
Thank you for your work.

**Comment by AndrewBabbitt97** [comment]
Should be fixed in the ChromaControl beta: https://github.com/ChromaControl/ChromaControl/releases/tag/msix-beta

At least startup should be fixed.

AuraConnect isn't supported anymore and replaced my ChromaControl.

On another note laptop's aren't supported, AuraSDK doesn't return laptops as controllable devices. You can always try it, but I make no promises of it working. The original intent for this was just ASUS desktop motherboards.

**Comment by w1nterB** [comment]
Thanks for the response.
That clarifies a lot of things. 
Thanks mate. Have a good day, Ill drop in again if it works.

**Comment by w1nterB** [comment]
Gday Andrew.
I can confirm it shows up in Synapse, and I'm now able to control all of my laptops's RGBS. Good on you mate. Thanks a ton!
