### ISSUE TITLE
Synapse sees Aura connect but Armoury seems to override

### ISSUE THREAD

**Issue by EliasRyker** [AndrewBabbitt97/AuraConnect#122]
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/6032695/AuraConnect.log)
So, Im using this setup:

ASUS TUF z490 Plus
ASUS ROG STRIX LC360 RGB Water-Cooling
6 ARGB Coolermaster Fans conected to an A-RGB Controller

Everything gets detected in armoury crate and I can set colours or effect for any of the components, but I cant manage to sync it with my razer peripherals:

Deathader
Blackwidow
Kraken Ultimate 
Headphone Stand

Anyideas?

**Comment by AndrewBabbitt97** [comment]
1. Use [ChromaControl](https://github.com/ChromaControl/ChromaControl/releases/tag/msix-beta) instead. This project is going to be archived and development is being moved there.

2. Your logs tell be everything is working correctly, don't open/use Armory Crate to control your ASUS devices RGB with this. Open Synapse 3 and you should see an ASUS device. Go over to the studio tab and make sure you set the device to have an effect.
