### ISSUE TITLE
Lights sync for a bit, then stop syncing.

### ISSUE THREAD

**Issue by bobfoowarp** [AndrewBabbitt97/AuraConnect#124]
My lights will sync up perfectly with wallpaper engine and my ram sticks (made by a different company). After around 10 seconds, the lights stop syncing to the wallpaper and ram sticks, which still sync. I think it is because AuraConnect stops running. But when I right click and start AuraConnect again in Task Manager, it doesn't change anything.

**Comment by AndrewBabbitt97** [comment]
AuraConnect has been archived, please move onto the replacement ChromaControl: https://github.com/ChromaControl/ChromaControl
