### ISSUE TITLE
Auraconnect plug-in not working.

### ISSUE THREAD

**Issue by Yajur28** [AndrewBabbitt97/AuraConnect#125]
My aurasync was working through razer synapse just fine until this early morning when I was trying to change the colour of the lighting through razer synapse until it just won’t change. I have reinstalled all 3 of the apps(aura connect, armoury crate and razer synapse 3) whenever I go to the page where I can change the colours. Under the chroma connect tab, under the asus plugin. There is an error warning telling me to make sure “make sure asus is running and chroma connect is enabled” when chroma connect was on and I went into the task manager and under services tab there was a program named “asus” which was stopped and I tried to start it but the second I started it. It got stopped instantly automatically. Please tell me how to fix this issue.

**Comment by AndrewBabbitt97** [comment]
AuraConnect has been archived, please move onto the replacement ChromaControl: https://github.com/ChromaControl/ChromaControl
