### ISSUE TITLE
Wallpaper engine stopping Auraconnect service to stop please help!!

### ISSUE THREAD

**Issue by Setzer123** [AndrewBabbitt97/AuraConnect#126]
I have installed and reinstalled everything a few times and I am having the same issue every time. Everything is working fine until I start Wallpaper Engine and the service stops. In Razer Synape the Aura Icon is there but says unreachable. I can start the service again but it just keeps saying unreachable and then stops again. If I close wallpaper Engine and then start and start Aruaconnect in Razer it will start working again. Please help?!

**Comment by AndrewBabbitt97** [comment]
AuraConnect has been archived, please move onto the replacement ChromaControl: https://github.com/ChromaControl/ChromaControl
