### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by KowalskiXCIX** [AndrewBabbitt97/AuraConnect#13]
How do we uninstall this program

**Comment by AndrewBabbitt97** [comment]
Same way as other programs, the installer creates uninstall entries in the Uninstall portion of control panel and the settings app in Windows 10. The entry is called "AURA Connect"

**Comment by AndrewBabbitt97** [comment]
I'm guessing you got it figured out, if you need anything feel free to reopen the issue.
