### ISSUE TITLE
Synapse just connected once to Aura

### ISSUE THREAD

**Issue by Zkore** [AndrewBabbitt97/AuraConnect#14]
I was able to get Aura Connect to work once, then rebooted and it stopped working and just makes Aura stop working, tried reinstalling everything to no success. 
attaching log file.
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4111708/AuraConnect.log)

**Comment by Zkore** [comment]
Latest version of aura, aura connect and razer synapse 3

**Comment by Paszak** [comment]
Hi, I had a similar problem. After turn off my Kasperscy Internet Security, AuraConnect has finished syncing.
I didn't get any notifications from the antivirus that something was blocked

**Comment by AndrewBabbitt97** [comment]
This looks to be antivirus blocking the connection. Synapse uses an HTTP connection on the local machine to communicate with other software, some antivirus can interfere with this.

We have also noticed something similar with anti cheat software doing something similar. Disable antivirus if you have it and test, report back after.

**Comment by AndrewBabbitt97** [comment]
@Zkore Can you confirm if this is related to antivirus?

**Comment by Zkore** [comment]
Effectively, it was kapersky antivirus blocking it, once the corresponding programs were allowed, everything worked as expected. Thanks
