### ISSUE TITLE
Cant Launch the app

### ISSUE THREAD

**Issue by Grunguiestooth** [AndrewBabbitt97/AuraConnect#15]
I have an Asus ROG strix GTX 1660 Ti 
But it not works apparently. WHEN I open the app, opens CMD and shows me error and then close too fast. tried to uninstall the software and reinstalling, same with the default software from the graphic card and nothing 
![image](https://user-images.githubusercontent.com/60502059/73569195-898b9780-442f-11ea-97b0-8a84644610c0.png)
![image (1)](https://user-images.githubusercontent.com/60502059/73569197-8b555b00-442f-11ea-98df-4dcb69e52412.png)
That's the only thing that need to complete my RGB SETUP

Thermaltake FANS
Lian Li 011 Dynamic Razer
Razer Nommo Chroma
Razer Firefly
Razer Mamba TE
Razer Ornata
Ryzen 2700X Wraith Prism

**Comment by AndrewBabbitt97** [comment]
It looks like ASUS Aura is not correctly installed, make sure you have a recent version of Aura installed correctly. This error is saying that the ASUS Aura COM component isn't registered properly on your computer. Without it AuraConnect won't work.

**Comment by AndrewBabbitt97** [comment]
Also, the program should not be started from the .exe file. Always run it from the service in the task manager. Errors can be collected using the log files in c:\ProgramData\AuraConnect

**Comment by AndrewBabbitt97** [comment]
I'll take a guess that you got this figured out. Feel free to reopen this issue if needed.
