### ISSUE TITLE
Aura lights doesn't work when a Hue Bridge is connected

### ISSUE THREAD

**Issue by ishanka25** [AndrewBabbitt97/AuraConnect#16]
I have a hue bridge connected to synapse also. When i turned on the hue strp through the synapse Hue section, the aura lights turns off. They won't turn back on until i disconnect hue strip. But with synapse visualizer, all the lights are working.

**Comment by AndrewBabbitt97** [comment]
This sounds like an issue with Synapse/Hue. There's nothing I can do on this front. This issue is unrelated to AuraConnect unfortunately.

Please report this on the Razer Insider forums for support in this area.
