### ISSUE TITLE
Auraconnect not reconnecting after restart of service

### ISSUE THREAD

**Issue by FearNaBoinne** [AndrewBabbitt97/AuraConnect#17]
Auraconnect started using up 39% of my CPU (Ryzen 7 3800x) when using the fire effect. (I know it'll use more cpu, but other apps like the Thermal Take and AsRock RGB Sync do not use that much more, but that is not what this issue is about!)

When I stopped the service, it went down as expected. 
When I restarted the service, it didn't reconnect to either Razer Synapse or Asus Aurasync (can't really tell from here which one it is!)

Haven't tried rebooting yet, but I assume it would work again then!

**Comment by AndrewBabbitt97** [comment]
If after you restart the service the Aura devices stay on one color/off chances are that it's Synapse having issues.

I have seen this, sometimes trying to reconnect to Synapse won't work and you have to restart Razers services/your computer to get it to work again. There's nothing I can do about this as this is an issue with Razers connect library talking to Synapse.

As for CPU, this is actually down to Aura's SDK being pretty brutal on updating LEDs. Synapse sends a ton of updates really fast to change LEDs and it means we call out to the Aura SDK a lot. The calls to AURA are pretty CPU intensive and this is another area I have no control over aside from hoping ASUS improves the performance of their SDK.

**Comment by FearNaBoinne** [comment]
I hear you! Aura Sync is pretty crappy. I'm actyally considering just setting the videocard lights to OFF, as that is better than a non-matching color *or* huge CPU loads...

Perhaps there is a possibility to throttle those requests? A configuration option to say "only allow updates every x milliseconds, and then skip the rest"?

**Comment by AndrewBabbitt97** [comment]
This is something I have considered looking into, the experience will definitely be worse in terms of look (essentially forcing frame drops) so animations will become choppier. The reason this sucks is because there's already a significant delay updating all of the LEDs even once as the calls to Aura take a while as is, so animations already lag behind because of this.

I may start an experimental branch to play around with some stuff like this.

**Comment by FearNaBoinne** [comment]
LOL, it might make it look better because the frames that aren't dropped are closer to the rest...

(I knew I shouldn't have gotten the Asus Strix 1070Ti, but the price was too good!)

**Comment by AndrewBabbitt97** [comment]
I have some ideas for this, gonna build a benchmark tool and some other stuff out to see what I'm going to do about this.

**Comment by AndrewBabbitt97** [comment]
I have added performance metrics to the latest build: https://github.com/AndrewBabbitt97/AuraConnect/releases/tag/1.0.3

Please follow the instructions here: https://github.com/AndrewBabbitt97/AuraConnect/blob/master/docs/PerformanceMetrics.md

Upload your log file after a while so I can see the performance metrics, this will allow me to investigate performance related issues.

**Comment by AndrewBabbitt97** [comment]
Haven't heard back on this, gonna close this stale issue. If problems persist let me know.
