### ISSUE TITLE
Razer Firefly

### ISSUE THREAD

**Issue by MrMaik7** [AndrewBabbitt97/AuraConnect#2]
The Razer Firefly Mousepad wont Show up in Chroma Studio anymore

**Comment by AndrewBabbitt97** [comment]
This program doesn't effect other devices in Synapse, it uses the standard Razer Broadcast API. It doesn't even have the ability to modify/read any Synapse devices.

Please ensure you don't have any other RGB software (like Jacknet) that may be causing this.

**Comment by AndrewBabbitt97** [comment]
As far as I can tell this is not an issue with this project but rather a system/software issue with synapse.

Closing this, please reopen if needed.
