### ISSUE TITLE
Chroma Compatible Games do not effect lighting

### ISSUE THREAD

**Issue by ZangLucarson** [AndrewBabbitt97/AuraConnect#21]
While watching a demo of how this application works I saw that the lighting was being affected by in-game events due to Chroma compatible games. This was a feature that had drawn me towards the application and when I tried it for myself, the lighting effects simply stayed the same as what I had set them to previously in Synapse. Does this feature only work for a few select games out of the already Chroma compatible games or is something wrong?

**Comment by AndrewBabbitt97** [comment]
It should work on every chroma compatible game, there is no logic in my code to determine this.

This program just listens to Synapse to know what to do.

Synapse just sends messages telling Aura connect what color devices should be and AuraConnect just applies that color to all Aura devices. We don't handle any of the logic relating to games working with Synapse.

**Comment by AndrewBabbitt97** [comment]
Also, make sure your game shows up in the connect tab on Synapse:

![Untitled](https://user-images.githubusercontent.com/2308261/77114052-7e95c200-69f1-11ea-8fa6-3ebe110d0b59.png)

**Comment by AndrewBabbitt97** [comment]
I'm going to assume you figured this out. Feel free to reopen if needed.
