### ISSUE TITLE
AuraConnect using 40-60% CPU sometimes

### ISSUE THREAD

**Issue by MChirodea** [AndrewBabbitt97/AuraConnect#22]
As the title suggests, sometimes, when starting the computer, AuraConnect uses 40%-60% CPU (This happens at an average of a few days). A workaround for this is simply restarting the service. Mind you, I reinstalled it once and this happens when the computer is shutdown and still receiving power. Haven't tested with the computer unplugged. My usual usage is around 2%. I'll attach the log file, in it, where it says it's starting, it's me restarting the service.
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4333984/AuraConnect.log)

**Comment by AndrewBabbitt97** [comment]
So let me understand a bit better,

This happens when the computer is shut down? I'm very confused by this statement as my software can't run with the computer shut down. How are you monitoring CPU usage when the computer is shut down?

**Comment by MChirodea** [comment]
No, sry, I may have created this confusion, after I shutdown the computer, next time I start the pc, Aura Connect sometimes uses 40-60% cpu

**Comment by MChirodea** [comment]
And it stays like that until I manually restart the service

**Comment by MChirodea** [comment]
After which it goes back to using 2%

**Comment by AndrewBabbitt97** [comment]
Do you have another log, more recent? Also what antivirus are you using?

**Comment by MChirodea** [comment]
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4345436/AuraConnect.log)

No antivirus, just windows defender

**Comment by AndrewBabbitt97** [comment]
What lighting effect is it on when it uses high CPU?

**Comment by MChirodea** [comment]
I had it set to default spectrum cycling

**Comment by MChirodea** [comment]
And later changed it to a custom spectrum cycling with slow motion thinking that was at fault. It wasn't tho.

**Comment by AndrewBabbitt97** [comment]
See how your CPU usage stands when you set it to static and report back.

**Comment by AndrewBabbitt97** [comment]
Also what CPU do you have?

**Comment by MChirodea** [comment]
Ok, I'll set it to static and see what happens. I have a Ryzen 7 1700x

**Comment by MChirodea** [comment]
Hello, so It did it again today, with static being set

**Comment by MChirodea** [comment]
Interesting thing tho, when the computer started it was using 3.9%, started playing destiny, and I saw my frame was chugging, and when i checked , auraconnect was at 37% ish.
![ecfe3fed4bac7a6708c92bdfdaf8bc80](https://user-images.githubusercontent.com/37183680/77745611-42cbaf80-7024-11ea-8772-8b03fb858321.png)
![d188edcfb79d61229bd203ccb996e6c1](https://user-images.githubusercontent.com/37183680/77745620-44957300-7024-11ea-9d85-1ee2568a1b3c.png)

**Comment by MChirodea** [comment]
To be precise, I kept a close eye on it for a few minutes when the pc started, it was originally at 1.2% and it started going up, it went to 3.9%, decided to play something, fast forward 2 hours, it was at 37% already

**Comment by MChirodea** [comment]
I'll attach here the log again, at the end i restarted the service, it now uses 0.1%
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4392752/AuraConnect.log)

**Comment by MChirodea** [comment]
Day 2, started the pc, left it for an hour alone, CPU usage went up to around 9% from 2% where it started.

**Comment by MChirodea** [comment]
After restarting the service, it is constantly at 0.1% ish. It only goes up after I start the computer. I'd like to mention that I have fast startup enabled in windows 10. Could this affect it?

**Comment by AndrewBabbitt97** [comment]
I'm hoping to release a performance based update today.

However, your log looks normal. It seems to be something on the Aura/Synapse side.

If you could close the LightingService or Synapse when at high CPU usage and see how the AuraConnect process changes that would be helpful.

**Comment by MChirodea** [comment]
That could actually be the case, i’ll try that when it happens again

**Comment by AndrewBabbitt97** [comment]
I have added performance metrics to the latest build: https://github.com/AndrewBabbitt97/AuraConnect/releases/tag/1.0.3

Please follow the instructions here: https://github.com/AndrewBabbitt97/AuraConnect/blob/master/docs/PerformanceMetrics.md

Upload your log file after a while so I can see the performance metrics, this will allow me to investigate performance related issues.

**Comment by AndrewBabbitt97** [comment]
Have you tried this?

**Comment by MChirodea** [comment]
Hello, yes, i tried, and hasn’t done it again, mby the reinstall helped? If it happens again, i’ll open another issue. Thank you for the help and time!
