### ISSUE TITLE
Battleye Kills AuraConnect

### ISSUE THREAD

**Issue by flameoffeanor** [AndrewBabbitt97/AuraConnect#23]
Hi, my motherboard (TUF B450 Gaming) works great with Razer Synapse but when i start a game (Rainbow Six Siege) it become "Unreachable" in Synapse.  In Armoury Crate: "Aura Sync is on standby, please choose an effect." 

![1](https://user-images.githubusercontent.com/62253585/76774002-65540200-67b4-11ea-8cfd-05a87110514f.jpg)

I should reinstall "AuraConnect" to fix it. 

[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4338936/AuraConnect.log)

Is there any other fix or am i doing something wrong?

**Comment by weavedawg74** [comment]
I run into the same issue with Siege. I believe it has something to do with Battleeye the games anti-cheat software. Every other game works great though.

**Comment by AndrewBabbitt97** [comment]
I actually play Siege myself, just not recently.

I would not be surprised if it was Battleeye as it has caused me numerous pains in the past, and if it is there's not a whole lot I can do about it. As it's Synapse saying it's unreachable, I assume Battleeye is blocking the connection between my service and Synapse. So the only way to fix that would be to remove Battleeye.... Which isn't really viable 😅

**Comment by AndrewBabbitt97** [comment]
If anyone has another Battleeye enabled game, could you test it and see if the same issue occurs? If so I may be able to take this up with the devs of it to get it resolved.

**Comment by AndrewBabbitt97** [comment]
I can confirm that this is an issue with BattleEye, ill try to see about reaching out to them and getting this resolved.

**Comment by AndrewBabbitt97** [comment]
Out of curiosity, do both of you have cortex with boost enabled? I noticed something being that the AuraConnect service was entirely killed off my machine when starting R6S.

**Comment by flameoffeanor** [comment]
> Out of curiosity, do both of you have cortex with boost enabled?

i didn't understand what you mean by that.

**Comment by weavedawg74** [comment]
I have disable Cortex because it kills the process in any game when it does its optimizing.

**Comment by AndrewBabbitt97** [comment]
@flameoffeanor Did you install Razer Cortex?

**Comment by flameoffeanor** [comment]
> @flameoffeanor Did you install Razer Cortex?

No, i didn't install Cortex. Only Synapse.

**Comment by AndrewBabbitt97** [comment]
I have sent an email to the Battleye team to get support on getting AuraConnect white listed, I'll update this issue as we make progress.

**Comment by AndrewBabbitt97** [comment]
Just want to let everyone know I am still tracking this, not really getting any response from the Battleye team which is honestly terrible.

I may be able to implement an intern solution that restarts the service when certain programs are running, but this may or may not work and I'm not sure what Battleye does to determine if an executable should be killed. It's a pain.

**Comment by AndrewBabbitt97** [comment]
Small update:

I did get a response from their support


```
Dear Andrew,

Unfortunately some software seems to interfere with BE on your system. Please be sure to follow the solutions mentioned in our FAQ (including adding exceptions to your anti-virus, etc.).

If nothing helps I'm afraid I can only suggest a Windows repair install since it's almost impossible to find out what it is causing this. You can find information on how to perform a repair install for your particular system by searching on Google (for example, see http://www.pcworld.com/article/243190/how_to_repair_a_corrupt_windows_7_installation.html).

Your BattlEye Support Team

We hope this response has sufficiently answered your questions. If not, please reply to this email.
```

**Comment by flameoffeanor** [comment]
Seems like BattleEye doesn't kill Aura Connect anymore :)

**Comment by AndrewBabbitt97** [comment]
Haven't had much want to play siege lately so I haven't been able to tell, but if this is the case this is great news.

I don't believe they ever got back to me on my last email, but I'll confirm this soon and close after.
