### ISSUE TITLE
Display of Asus Ryujin work while AuraConnect active?

### ISSUE THREAD

**Issue by tark95** [AndrewBabbitt97/AuraConnect#24]
First of all, this is not really an issue but I didn't know where else to put this.

It's about the Ryujin cooler from Asus. This AIO cooler has a display on the pump in addition to an LED strip. I was wondering if you could mess around with the display while the LED strip syncs up with Synapse/AuraConnect.

Is anybody using the Asus Ryujin cooler and can report on this?

**Comment by AndrewBabbitt97** [comment]
That display is on some ASUS motherboards as well, its called LiveDash.

You can change it with the LiveDash application.

Closing this issue, this is not the place to ask about this.
