### ISSUE TITLE
Cannot use with ArmoryCrate (Aura sync successor)

### ISSUE THREAD

**Issue by kbrighton** [AndrewBabbitt97/AuraConnect#29]
So, I've been attempting to use this with ArmoryCrate, which is the Aura sync successory.  I've gotten it to see the Aura Sync device, which is a ROG Hero Maximus X motherboard, with Aura compatible Ram and an Aura Compatible case.  According to the logs, it sees them, but I don't think it's actually sending any RGB data through ArmoryCrate/Aura, since turning on the enhanced logging hasn't shown anything.

[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4429472/AuraConnect.log)

**Comment by AndrewBabbitt97** [comment]
So it looks like this is actually on the Synapse side, the synapse library sends messasges to AuraConnect to change the colors of devices but this message isn't happening at all.

Please confirm the existence of the following files:

C:\Program Files\Razer\ChromaBroadcast\bin\RzChromaBroadcastAPI64.dll
C:\Program Files\Razer\ChromaBroadcast\bin\RzChromaBroadcastManager64.dll

C:\Program Files (x86)\Razer\ChromaBroadcast\RzChromaBroadcastAPI.dll
C:\Program Files (x86)\Razer\ChromaBroadcast\RzChromaBroadcastManager.dll

Also if you can zip up all the log files in C:\Program Files (x86)\Razer\ChromaBroadcast\logs or C:\Program Files\Razer\ChromaBroadcast\logs and add them?

**Comment by kbrighton** [comment]
Both 32 and 64bit versions of those libraries exist.

I'm attaching the log files. They're pretry small.
[Razer Synapse Service.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4429954/Razer.Synapse.Service.log)
[RzSDKService.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4429955/RzSDKService.log)
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4429956/AuraConnect.log)

**Comment by kbrighton** [comment]
So, strangely enough it just started working now, though it's running a bit slow on the ASUS stuff and the addressable header.  I'll post the log.
[AuraConnect.zip](https://github.com/AndrewBabbitt97/AuraConnect/files/4457933/AuraConnect.zip)

**Comment by kbrighton** [comment]
Well, strange again, it was working, and when I turned off the performance metrics I it stopped working.  It's probably unrelated, but now I'm seeing this in the logs:

2020-04-09T15:35:52.8499200-04:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Application started. Hosting environment: Production; Content root path: C:\Program Files (x86)\ASUS\AURACONNECT\
2020-04-09T15:35:53.8583492-04:00	INFO	[AuraConnect.Worker]	[Logging]	Initializing Aura Connect...
2020-04-09T15:36:40.7797462-04:00	INFO	[AuraConnect.Worker]	[Logging]	Found Device: AURA - Dram 1 - 5 Lights
2020-04-09T15:36:40.7799493-04:00	INFO	[AuraConnect.Worker]	[Logging]	Found Device: AURA - Dram 2 - 5 Lights
2020-04-09T15:36:40.7799844-04:00	INFO	[AuraConnect.Worker]	[Logging]	Found Device: AURA - Dram 3 - 5 Lights
2020-04-09T15:36:40.7799953-04:00	INFO	[AuraConnect.Worker]	[Logging]	Found Device: AURA - Dram 4 - 5 Lights
2020-04-09T15:36:40.7800075-04:00	INFO	[AuraConnect.Worker]	[Logging]	Found Device: AURA - Mainboard_Master - 5 Lights
2020-04-09T15:36:40.7800244-04:00	INFO	[AuraConnect.Worker]	[Logging]	Found Device: AURA - AddressableStrip 1 - 120 Lights
2020-04-09T15:36:40.7800393-04:00	INFO	[AuraConnect.Worker]	[Logging]	Aura Connect started successfully!
2020-04-09T15:36:41.7779277-04:00	INFO	[AuraConnect.Worker]	[Logging]	Razer Chroma Broadcast API disconnected
2020-04-09T15:36:45.7932157-04:00	INFO	[AuraConnect.Worker]	[Logging]	Razer Chroma Broadcast API disconnected
2020-04-09T15:36:49.8045407-04:00	INFO	[AuraConnect.Worker]	[Logging]	Razer Chroma Broadcast API disconnected
2020-04-09T15:36:53.8132543-04:00	INFO	[AuraConnect.Worker]	[Logging]	Razer Chroma Broadcast API disconnected
2020-04-09T15:36:57.8655636-04:00	INFO	[AuraConnect.Worker]	[Logging]	Razer Chroma Broadcast API disconnected
2020-04-09T15:37:01.9298382-04:00	INFO	[AuraConnect.Worker]	[Logging]	Razer Chroma Broadcast API disconnected
2020-04-09T15:37:05.9867683-04:00	INFO	[AuraConnect.Worker]	[Logging]	Razer Chroma Broadcast API disconnected

**Comment by AndrewBabbitt97** [comment]
Can you do me a favor. Try to run this in Windows safe mode. You will probably have to turn on LightingService and stuff manually, but I'm curious as to off it works. It really sounds like something is interfering with the application.

**Comment by kbrighton** [comment]
Tried that, lighting service wouldn't start in safe mode.  I also went and changed a setting in Kaspersky Cloud to see if that works, and after the reboot it started up again and is working.  However, despite me setting the metrics to false, it's still giving me metrics logs.

**Comment by AndrewBabbitt97** [comment]
Oof Kaspersky....

I already know there's issues with running Kaspersky. It is known to interfere with the connection between AuraConnect and Synapse. There's not really anything I can do on this side to fix that. I'm not even sure where to start with getting support from a company like Kaspersky. I personally use built in Windows Defender as it has gotten remarkably better over the years.

As for still collecting metrics logs, Windows sometimes does some weird stuff with restarts and services. So stop the service, ensure the value in the config file is set to false, and turn the service back on.

**Comment by kbrighton** [comment]
Then that's probably the issue, and it probably works sometimes depending on the order of starting, with regards to Kaspersky.  I'll shut down aura connect, pause kaspersky, and see if that fixes anything.

**Comment by kbrighton** [comment]
And yep, paused Kaspersky and it came up just fine, and continued working after I resumed protection, so it looks like that was the issue.  Thanks for the help troubleshooting it.  I do wonder what's causing it, though.

**Comment by AndrewBabbitt97** [comment]
So Razer Synapse has a service and AuraConnect connects to. Its a network connection just on your local machine. Kaspersky seems to block connection attempts to the Razer service so AuraConnect just keeps printing out the disconnected message in the log. However once this connection is established, Kaspersky doesn't break it. It just prevents it from connecting at the start.

**Comment by AndrewBabbitt97** [comment]
I'd say your best bet to not have to do that all the time is to find a way to exclude all Razer and AuraConnect files. If this doesn't work then I don't know if there's much we can do about it, it's just how Kaspersky is designed to work.

**Comment by kbrighton** [comment]
Let me do some configuration stuff with Kaspersky, and I might be able to find a quick solution.

**Comment by AndrewBabbitt97** [comment]
Let me know where you get, I would like to get a FAQ up with common issues here soon and add stuff like this for future reference.

**Comment by kbrighton** [comment]
I'll spend some time tomorrow doing it, since I've got the day off.  I'll let you know if I can figure anything out.  Turning off the firewall and restarting doesn't do the trick, so it must be something else that's blocking local network connections.

**Comment by OAlienado** [comment]
If only I knew about the Kaspersky stuff... After all that trouble , all of sudden it stopped working. But now I know it was not "all of sudden", it was "after reinstalling Kaspersky" -_-

**Comment by OAlienado** [comment]
Just to update, with Kaspersky closed, everything worked flawlessly. I can now even sync my corsair memories, since they are are controlled with Armoury Crate with the corsair plugin for aura. Thank you again!

Just for the record, @AndrewBabbitt97, is there any other antivirus know for causing such trouble? Thank you!

**Comment by AndrewBabbitt97** [comment]
Gonna close this issue since we know what's going on.

I am not aware of any other antivirus software causing issues at this time. There could be others, but I use Windows Defender as my choice and don't run into any issues.
