### ISSUE TITLE
Razer Mamba 

### ISSUE THREAD

**Issue by MrMaik7** [AndrewBabbitt97/AuraConnect#3]
Effects wont apply on Razer Mamba

**Comment by S3bTheGuy** [comment]
Will I have to close razed synapse 3 and asus aura too???

**Comment by AndrewBabbitt97** [comment]
Restart your PC after installing and report back how it is.

I have already tested with a Firefly and Mamba and both work on my side on 2 different PCs.

If worse comes to worse I would reinstall all 3 pieces (Synapse, Aura, and AuraConnect).

**Comment by S3bTheGuy** [comment]
Ok I’ll try to re-install aura because every time I try to use it my aura just stops

**Comment by AndrewBabbitt97** [comment]
I would recommend against using aura to control any lights when this software is installed.

With this you control ASUS devices with synapse, if synapse is missing a device please consider reinstalling it.

This software does not interact with other Razer devices, looks to be an issue with your hardware/software setup on your PC.

Tested with a Mamba today and all looks fine.

Please open this issue if you feel that there is something else needed.
