### ISSUE TITLE
Tarkov BattlEye Kills AutoConnect

### ISSUE THREAD

**Issue by alexrotondo** [AndrewBabbitt97/AuraConnect#30]
Hello!

Thanks so much for this software its amazing. I tested it with a ton of Chroma games and have a blast using it. Only issue I have is Battleye in Escape From Tarkov kills AuraConnect and on relaunch gets 
info: AuraConnect.Worker[0]  Initializing Aura Connect... If you could fix this I would donate $20 because this is the only game I play lol. Awesome work dude!

![image](https://i.imgur.com/UtbOgL6.jpg)

**Comment by AndrewBabbitt97** [comment]
I'm aware of this issue. I personally can't do anything on this, it's up to the Battleeye team to fix this as it's their software causing this issue.

**Comment by AndrewBabbitt97** [comment]
Keep in mind we are tracking this on #23 

I have sent an email out to the Battleye team to get this fixed.
