### ISSUE TITLE
its not an issue but a feature request

### ISSUE THREAD

**Issue by 1988fido** [AndrewBabbitt97/AuraConnect#31]
hi 

your plugin is amazing and solve a big issue for me , thanks , anyway I wish if there is a way to chose what will sync exactly , as right now my ram,cpu block, motherboard , and gpu all being synced with chroma I want to be able to chose only ram+motherboard for example if possible :D

**Comment by AndrewBabbitt97** [comment]
If I were to implement this, there's one thing you would have to be aware of:

If the device is controlled by AURA and I exclude it, nothing else will be able to control it. It will be stuck on whatever color the device was at when AuraConnect starts controlling the other devices. We can't selectively control individual devices with AURA, it's kinda an all or nothing. It's just how the AURA SDK works.

**Comment by tchesket** [comment]
I read up a little bit on Armory Crate, and that includes a way to control different components individually, is this separate from what you're using to interact with Aurasync? Or is it possible to get Chroma to use these controls?

**Comment by AndrewBabbitt97** [comment]
AuraSync takes exclusive control of all devices in Aura, this is how Aura and the Aura SDK works. You should not be using Aura/Armory Crate or any other tool to mess with Aura if you use AuraConnect. You cannot change things on that side when using AuraConnect.

**Comment by tchesket** [comment]
Okay thanks for the clarification. In all honesty, I haven't actually used
AuraSync yet, I just ordered all the parts for a new PC with it and was
doing some preliminary research. Aside from AuraConnect though, do you
happen to know if such a tool would be possible/practical to create from
scratch? Sorry if this is a silly question, like I said I know very little
about it. Thanks.

**Comment by AndrewBabbitt97** [comment]
Unfortunately it would not be practical, you would essentially have to make your own version of AURA to do such a thing. We do not have the source code for AURA, and the undertaking for such a thing would be massive. It's really just not a viable thing to do, just the sheer amount of work to support every device made by a manufacturer would be a huge amount of work.

**Comment by AndrewBabbitt97** [comment]
Closing this for the time being.
