### ISSUE TITLE
Interesting interaction between AuraConnect, Wallpaper Engine and Corsair iCue

### ISSUE THREAD

**Issue by OAlienado** [AndrewBabbitt97/AuraConnect#32]
Hello again! Just noticed something interesting that I'd like to share...

So, I have 4 Corsair Vengeance Pro RGB memories, all previously controlled by Armoury Crate using the Corsair Plugin. For my surprise, when I installed AuraConnect and Razer Synapse, the bound between iCue and Aura was not broken, and so I got the memories in sync with the rest of the setup while under Synapse's control.

After that, I installed Wallpaper Engine, wich works with both Razer Chroma SDK and Corsair iCue SDK.  So, I fire it up and... all my lights got stuck. I checked the Task Manager and, for my surprise, the AuraConnect service stopped all by itself. After restarting the service and reopening Synapse, everything got back to normal - including my memories - without rebooting the PC.

I did some testing and figure that, when the iCue extension was off in the Wallpaper Engine settings, there is no issues. I am not sure if this happen because of the Corsair Aura Plugin, but, in my previous instalation (before I managed to make the Corsair Aura Plugin work...) I got both Synapse and iCue work alongside Wallpaper Engine without problems - and, oddly enough, the effect show by the memories back there was different than the one they show under Synapse with AuraConnect.

Unfortunally, I don't have the logs, because... I don't know how to set the AuraConnect to make them ^^'' (noob here, sorry =/)

Anyway, I just wanted to share this issue. in hope it helps to improve the software somehow. Feel free to close the thread and, once more, thanks again @AndrewBabbitt97 for all the good and hard work!

**Comment by AndrewBabbitt97** [comment]
So there's nothing I can do on this, this issue lies within the RGB SDKs and not my software. It's a mess with the sound of that, 3 different RGB SDKs and software wanting to control multiple. Something's bound to go wrong because SDKs take exclusive control over the devices, only one app can have control at a time.

Not something I plan to investigate much, thanks for bringing it up though.
