### ISSUE TITLE
Stuttering in Games with Auraconnect.exe opened

### ISSUE THREAD

**Issue by dmbrio22** [AndrewBabbitt97/AuraConnect#36]
Andrew,

First of all thank you for your work, wish more people were like you and ASUS is complete crap in software making.

I have noticed some major stuttering and lack of fluidity in Destiny 2 when using Auraconnect.

I spent something close to 2 hours trying to identify what was causing the issue.

CPU usage was not high nor anything, so I did not suspect it was Auraconnect initially. But through trial and error, as soon as I closed the application, my gaming experience was sky high again.

I am using your latest version.

9900k
2080 ti
Maximus XI Apex
Razer Huntsman and Viper Ultimate

**Comment by AndrewBabbitt97** [comment]
Is it only Destiny 2 that this happens in?

**Comment by dmbrio22** [comment]
I only play Warzone and D2, in D2 it was extremely noticeable, in Warzone not so much, but also improved a lot when I closed the app.

**Comment by AndrewBabbitt97** [comment]
I would like for you to try something:

1. Enable performance metrics logging, you can find out how here: https://github.com/AndrewBabbitt97/AuraConnect/blob/master/docs/PerformanceMetrics.md

2. Run through the games and upload your logs from C:\ProgramData\AuraConnect\logs

**Comment by AndrewBabbitt97** [comment]
Assuming you figured this out, feel free to reopen if needed.
