### ISSUE TITLE
Not working. 

### ISSUE THREAD

**Issue by Viper4060** [AndrewBabbitt97/AuraConnect#39]
AuraConnect Finds devices and lights but does nothing when setting any effect in Synapse. Aura does show up in Synapse as well. AuraConnect also stops all lighting control like it should in Aura and Armory Crate 
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4520082/AuraConnect.log)

**Comment by AndrewBabbitt97** [comment]
Please follow the instructions to enable metrics logging and upload a log after 10-15 mins of starting the service:

https://github.com/AndrewBabbitt97/AuraConnect/blob/master/docs/PerformanceMetrics.md

**Comment by Viper4060** [comment]
Ended up being a little more than 10-15 mins 
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4526257/AuraConnect.log)

**Comment by Viper4060** [comment]
@AndrewBabbitt97 before you ask yes I properly enabled metrics I just don't think it even getting that far.

{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "PerformanceMetricsEnabled": true
}

**Comment by AndrewBabbitt97** [comment]
Issue is that the Synapse components aren't working correctly. Please uninstall and reinstall all Razer software. Ensure when you reinstall the chroma connect module is selected for install.

**Comment by Viper4060** [comment]
Fresh installed synapse still having the exact same issue it does not say Unreachable. It's working just doing nothing.

**Comment by AndrewBabbitt97** [comment]
Gonna need another log with perf metrics, and a line in that log saying Razer Synapse connected. There needs to be a line as follows in your log file:

Razer Chroma Broadcast API connected

If no such line exists then there's something up with Synapse or a 3rd party program interfering with the software.

**Comment by Viper4060** [comment]
I can now get it to work I have to stop the process and manually run the exe as admin.

**Comment by AndrewBabbitt97** [comment]
Very weird for the service to not work, the service runs as system user by default unless you change it. This is the first instance that someone is unable to run it through the service (as it's supposed to be run). What windows build are you running?

**Comment by Viper4060** [comment]
Version 1909 (OS Build 18363.778)

**Comment by AndrewBabbitt97** [comment]
If you have the ability to dual boot and install on a completely clean install of windows and see if it works I'd love that, there's just not much in the way of me being able to diagnose this issue. I can only assume it is an issue with your particular setup/install. I haven't seen this issue before.

**Comment by AndrewBabbitt97** [comment]
Unless you can 100% confirm it's not an issue with your setup, there's not much I can do. If you are able to clean install and test, and one by one install programs until it breaks this would be helpful.

I'll be closing this issue, you may reopen it if you want to pursue that avenue and I'll assist however I can.
