### ISSUE TITLE
aura effect stops

### ISSUE THREAD

**Issue by S3bTheGuy** [AndrewBabbitt97/AuraConnect#4]
Hey i just tried it aura shows up in razer synapse but when i chech aura it runs an effect for 5 seconds then just freezes. its does not change when opening overwact i have also tried re-installing the apps
[video.zip](https://github.com/AndrewBabbitt97/AuraConnect/files/3714215/video.zip)

**Comment by AndrewBabbitt97** [comment]
Looking into this. Will probably make a diagnostic utility to see what's going on.

I'll throw a new comment when this is available.

**Comment by Rylleyryelle** [comment]
ive just started using this as i have razer keyboard and asus motherboard. wanted to link the effects from Razer Synapse Chroma becuase the default Aura ones are frankly junk.

After about 1-2 days my Aura stuff just stops responding and a simple way to fix it I've figured out is to just force-close AuraConnect.exe via task manager and reopen it.

**Comment by AndrewBabbitt97** [comment]
AuraConnect is a service, you can restart it from the service list if needed.

In most cases if it stops responding it's usually Synapse or Aura causing it.

Next time this happens please try exiting Synapse from the system tray and reopening and see if the effects resume instead of restarting AuraConnect.

**Comment by Rylleyryelle** [comment]
i tried restarting everyhing. Synapse, Aura, iCue, turning connect off and on again, and finally restarted AuraConnect and that fixed it.

**Comment by AndrewBabbitt97** [comment]
What is CPU/memory usage when it stops?

**Comment by Rylleyryelle** [comment]
constantly floating between 1.3-1.7% cpu load, and 24.1-25.3mb memory
Ryzen 7 3800X and 16GB DDR4

**Comment by AndrewBabbitt97** [comment]
Sounds like the service is still processing requests from Synapse then, looks like this is an AURA issue. When you restarted AURA what exactly did you restart?

**Comment by Rylleyryelle** [comment]
taskmanager -> details -> AuraConnect.exe
then reopened it from location
Currently its at 0% cpu and climbing in RAM. its up to 30.2mb. its like it drops a little then climbs a little. it hasn't crashed today yet, but i'll let you know what it is after work (about to leave for 8 hours lol)

**Comment by AndrewBabbitt97** [comment]
Keep me updated, when it freezes I'd like you to go to Task Manager -> Services -> LightingService and restart that from there by pressing the restart option in the right click menu.

You can do the same with AuraConnect.

**Comment by Rylleyryelle** [comment]
Rebooted the machine to have a clean timeline.
As of now: 0% CPU, 15.9mb

**Comment by Rylleyryelle** [comment]
hasn't stopped working yet, but back from work now and it looks like there might be a slight memory leak. its currently at 1.3% cpu and 158.2mb and climbing somewhat rapidly
![Taskmgr_2019-12-21_03-27-12](https://user-images.githubusercontent.com/22532776/71305425-cdf03600-23a1-11ea-8fd9-0f6dc97e81c0.png)

**Comment by Rylleyryelle** [comment]
well it got to about 600mb and stopped responding and windows reset it for me this time because the service stopped so now its back to 22mb

**Comment by Rylleyryelle** [comment]
so it finally crashed again while i was out for holidays. came back with it off, service stopped, and this in the event viewer.
![mmc_2019-12-27_16-46-04](https://user-images.githubusercontent.com/22532776/71533727-82211d80-28c8-11ea-8f13-8880828e60de.png)
![mmc_2019-12-27_16-46-26](https://user-images.githubusercontent.com/22532776/71533728-82b9b400-28c8-11ea-9d6c-a6c48f5171f1.png)
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" /> 
  <EventID Qualifiers="49152">7034</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8080000000000000</Keywords> 
  <TimeCreated SystemTime="2019-12-24T13:47:08.625209500Z" /> 
  <EventRecordID>33105</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="828" ThreadID="9804" /> 
  <Channel>System</Channel> 
  <Computer>Avalanthe</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="param1">AuraConnect</Data> 
  <Data Name="param2">1</Data> 
  <Binary>410075007200610043006F006E006E006500630074000000</Binary> 
  </EventData>
  </Event>

**Comment by AndrewBabbitt97** [comment]
I'm gonna add some extra logging and release a new build, after I'll need you to test again and give me the logs. I'll let you know when the release is available.

**Comment by apisselhoy** [comment]
First thanks for this project - I've been looking a long time for a possibility to sync Aura and Synapse.

Unfortunately, I have the same issue here - it works fine with my Asus Prime X570-P including addressable stripes and G.Skill-RAM for some time until the AuraConnect.exe service crashes. After starting the service and restarting synapse it works again but will crash again after a couple of minutes.
I have the same log entry in the system log as mentioned above and a corresponding log entry in the application log:

```xml
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2019-12-31T10:31:54.595669800Z" /> 
  <EventRecordID>7160</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>GameMachine</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>AuraConnect.exe</Data> 
  <Data>1.0.0.1</Data> 
  <Data>5d7bb0cb</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.18362.535</Data> 
  <Data>5bd9df62</Data> 
  <Data>e0434352</Data> 
  <Data>001135d2</Data> 
  <Data>3060</Data> 
  <Data>01d5bf487fa88c06</Data> 
  <Data>C:\Program Files (x86)\ASUS\AURACONNECT\AuraConnect.exe</Data> 
  <Data>C:\Windows\System32\KERNELBASE.dll</Data> 
  <Data>5850fcda-1aa8-44d7-8242-6cddad047029</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

**Comment by AndrewBabbitt97** [comment]
New release is out, please test this new release and let me know how things are in it:

https://github.com/AndrewBabbitt97/AuraConnect/releases/tag/1.0.1
