### ISSUE TITLE
Motherboard RGB is not synchronal

### ISSUE THREAD

**Issue by 7LEM0N** [AndrewBabbitt97/AuraConnect#40]
Everything works fine except the motherboard RGB, I'm not sure if I set it properly or it is a issue.
![51347](https://user-images.githubusercontent.com/64376965/80317275-df72a000-87d0-11ea-91a4-657500f8d998.jpg)

**Comment by 7LEM0N** [comment]
One more thing, when I use Chroma Visualizer, my Rog graphics card basically shows a single color but not flash synchronously with other devices. 
Anyway, thank you for developing this amazing plugin.
![53957](https://user-images.githubusercontent.com/64376965/80317899-81e05280-87d4-11ea-8506-6d1b00176c04.jpg)

**Comment by AndrewBabbitt97** [comment]
Need logs from C:\ProgramData\AuraConnect\logs

**Comment by 7LEM0N** [comment]
> Need logs from C:\ProgramData\AuraConnect\logs

[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4536433/AuraConnect.log)

**Comment by AndrewBabbitt97** [comment]
Please enable performance metrics and get me new logs: https://github.com/AndrewBabbitt97/AuraConnect/blob/master/docs/PerformanceMetrics.md

Your motherboard shows up in the logs so it sees it, however it isnt updating. This may be the fault of the AURA SDK, but hard to say.

**Comment by 7LEM0N** [comment]
> Please enable performance metrics and get me new logs: https://github.com/AndrewBabbitt97/AuraConnect/blob/master/docs/PerformanceMetrics.md
> Your motherboard shows up in the logs so it sees it, however it isnt updating. This may be the fault of the AURA SDK, but hard to say.

This is the new one.
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4536470/AuraConnect.log)

**Comment by AndrewBabbitt97** [comment]
That log isn't even showing the same issue, but potentially an entirely different one. With that log, none of your devices should be working at all. Is that the case?

**Comment by 7LEM0N** [comment]
> That log isn't even showing the same issue, but potentially an entirely different one. With that log, none of your devices should be working at all. Is that the case?

Actually everything works except the motherboard. All other devices work well in all RGB mode, and only in the Chroma Visualizer mode the graphics card is a little discordant.

**Comment by AndrewBabbitt97** [comment]
That last log says that AuraConnect isn't even talking to Synapse, and no performance metrics are being logged so no devices should be syncing at all. Please ensure you have enabled the logging and fully restarted the service, your log tells me no devices are working.

**Comment by 7LEM0N** [comment]
> That last log says that AuraConnect isn't even talking to Synapse, and no performance metrics are being logged so no devices should be syncing at all. Please ensure you have enabled the logging and fully restarted the service, your log tells me no devices are working.


Wow, the motherboard is working after I restarted the service again. However the graphics card RGB is still discordant in Chroma Visualizer mode. Its color is changing with other devices, but it can only show a single color while others are showing mixed color.

![92143](https://user-images.githubusercontent.com/64376965/80322439-37220300-87f3-11ea-98c0-8cf381341bf5.jpg)

[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4536658/AuraConnect.log)

**Comment by AndrewBabbitt97** [comment]
Thats because we only get 1 light on the GPU to control, its a limitation of the GPU/Aura Sync.

You can confirm this from the log, these values are reported from AURA:

Found Device: AURA - Vga 1 - 1 Lights

**Comment by AndrewBabbitt97** [comment]
Otherwise, everything is working as expected. I'd recommend disabling the performance metrics or the log will grow pretty massive.

**Comment by 7LEM0N** [comment]
> Otherwise, everything is working as expected. I'd recommend disabling the performance metrics or the log will grow pretty massive.

Ok, thank you so much. Your plugin is so amazing!!!
