### ISSUE TITLE
PC sleep breaks something

### ISSUE THREAD

**Issue by AAlchemy** [AndrewBabbitt97/AuraConnect#43]
I have to stop/start the AuraConnect service after the PC wakes from sleep to get RGB to start syncing again.

**Comment by AndrewBabbitt97** [comment]
Need your logs in C:\ProgramData\AuraConnect\logs in order to debug.

**Comment by AAlchemy** [comment]
nothing overly helpful, it just sets on 2020-05-03T16:45:03.4833590-04:00	INFO	[AuraConnect.Worker]	[Logging]	Initializing Aura Connect...

until I restart the service manually

[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4571628/AuraConnect.log)

**Comment by kooori** [comment]
I find when the computer goes to sleep the lights pause. I have it set in syanpse that the lights should turn off, the razer devices turn off but now the aura sync.

**Comment by AndrewBabbitt97** [comment]
Synapse setting only works on Razer devices, there's nothing I can do there. Believe you can control sleep settings for lighting in ASUS bios.
