### ISSUE TITLE
Not working on ASUS ROG Strix G531GT with Armoury Crate

### ISSUE THREAD

**Issue by sifarhalani** [AndrewBabbitt97/AuraConnect#45]
Hello,

I have installed the latest version of Armoury Crate and the latest version of Razer Synapse. I cannot get AuraConnect to appear on my Devices list in the Connect module of Synapse. What should I do?

Thanks.

**Comment by AndrewBabbitt97** [comment]
Need logs from C:\ProgramData\AuraConnect\logs

Make sure to restart your PC after the install

**Comment by sifarhalani** [comment]
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4597327/AuraConnect.log)

Here is the file you requested. I have restarted my PC multiple times.

**Comment by AndrewBabbitt97** [comment]
Looks related to #42 not something that is fixable on my side, we look to be waiting on ASUS/Microsoft for a fix.
