### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by cherrera1990** [AndrewBabbitt97/AuraConnect#46]
Hi!
I've tried everything (including different Aura versions, installing just the lighting service, Armory crate, etc...) with no avail. My logs just say this:
```
2020-05-10T20:34:29.5565812+02:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Application started. Hosting environment: Production; Content root path: C:\Program Files (x86)\ASUS\AURACONNECT\
2020-05-10T20:34:30.5580203+02:00	INFO	[AuraConnect.Worker]	[Logging]	Initializing Aura Connect...
```
And I can see it starting when I start it from the service tab in the task manger but then it dissapears.

I've also tried to run it from the .exe to see if I could catch a glimpse of the error in the cmd and I saw this:
![image](https://user-images.githubusercontent.com/12307722/81507827-3368a300-9300-11ea-91a9-56ac39c4713e.png)

I do have a RGB ram, a HyperX fury that can be controlled via Aura sync. Is there any workaround? 

Thanks!!

**Comment by AndrewBabbitt97** [comment]
3rd line in the console window indicates something is wrong with Aura. Are you using Armory Crate or Aura?

Also what windows build are you running? This may be related to #42

**Comment by cherrera1990** [comment]
Right now Aura v1.07.71 (but I have tried 7.79 and 06.17) and 1909 build. I have read the #42 issue, should I install armory crate again? My mb is a TUF z390-plus gaming if that helps, and no kaspersky istalled.

**Comment by AndrewBabbitt97** [comment]
You should use Armory if your motherboard supports it, always. Uninstall all existing Aura components then install armory.

**Comment by cherrera1990** [comment]
Hi!
I've unistalled all Aura components and installed armory and then AuraConnect, but still nothing. Same logs and same error.

**Comment by cherrera1990** [comment]
I have tried to reinstall windows and that did the trick. Now I can use it without any issue! 😃

**Comment by AndrewBabbitt97** [comment]
#42 also relates to a Windows issue, but it's hard to say what it may have been. Aura/Armory have been in an interesting spot lately, I'm hoping that things change soon on that front because I believe many opened issues may have been caused by it.

Feel free to reopen if needed, glad you got it working.
