### ISSUE TITLE
Impossible to open: The process cannot access the file log in ProgramData

### ISSUE THREAD

**Issue by sergiogomez-91** [AndrewBabbitt97/AuraConnect#48]
Hi Andrew.

Im trying to execute your app with my ASUS Rog Strix Z390-F and my Lian Li O11 Dynamic from Razer with the Synapse app and Im getting this error while I try to open it:

https://imgur.com/k94hTbO

Is there any solution?

Thanks.

**Comment by sergiogomez-91** [comment]
I closed the app and delete the log file and now it seems is working.

**Comment by AndrewBabbitt97** [comment]
App runs as a Windows service (admin privileges).

I'm guessing you were trying to run it from it's install location as a regular user, the log file was created as an admin user so only admins can write to it by default. This is why it couldn't write to it. 

You are not supposed to run the program manually, only as a Windows service.

**Comment by AndrewBabbitt97** [comment]
I mostly left the ability to run it manually for my own use, I should really remove that functionality in release builds ....

**Comment by sergiogomez-91** [comment]
Now I get this errror:

https://imgur.com/dZUCoVG

**Comment by sergiogomez-91** [comment]
When I run the AuraConnect.exe the cmd window doesn't close.

If I close the window, sync stop working.

Window I mean: https://imgur.com/a/6S5GdVj

**Comment by AndrewBabbitt97** [comment]
In your task manager there is a services tab, Aura Connect is in that list and should be stopped and restarted from there.

You edited out a response that had this image: https://imgur.com/dZUCoVG

That image is telling me that something is corrupted/wrong with your AURA/Armory Crate install because the Aura COM components weren't registered correctly on your PC.

**Comment by AndrewBabbitt97** [comment]
Also, the service is started with Windows by default so you shouldn't have to do anything to make it work.

**Comment by sergiogomez-91** [comment]
Yes I needed to restart.

Thank you dude :)

**Comment by sergiogomez-91** [comment]
BTW it would be great to have syncronization also with Gigabyte RGB Fusion program, for GPU cards :)

**Comment by AndrewBabbitt97** [comment]
Unfortunately I do not have any Gigabyte hardware, so it's not that easy for me to test these things along with keeping up with their software updates. :( Otherwise I would

**Comment by sergiogomez-91** [comment]
NP dude, thank you for the answers :)
