### ISSUE TITLE
Problems till 4 days ago

### ISSUE THREAD

**Issue by sancas** [AndrewBabbitt97/AuraConnect#49]
I have not been able to make this work again... it just stopped working since like 4 days ago, I try reinstalling and everything but i cant, synapse says everything ok, but not take control of lights, aura keep controling em i dont know what i did, could you help me please

[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4666608/AuraConnect.log)

**Comment by AndrewBabbitt97** [comment]
Did you have any windows updates around the same time?

**Comment by sancas** [comment]
I just checked that... and aura service from armoury crate just was updated may 15... I just re downloaded the add on I had beening using for connect my corsair with razer... using aura as a bridge, hjahahahaha, and it just start working nice again, sorry for disturb.

**Comment by AndrewBabbitt97** [comment]
All good
