### ISSUE TITLE
Not able to connect

### ISSUE THREAD

**Issue by Azrael0528** [AndrewBabbitt97/AuraConnect#50]
Hi,

Am not able to connect my Aura RGB to my Chroma Studio.

Its showing up on the Chroma Studio, but there has been no response or color highlight on it.

Please let me know if this is a known issue.

Thanks!

**Comment by Raidentaylor** [comment]
Hi.

I think you need to put logs. You use kaspersky? Try to disable anti-virus and restart asus connect.

**Comment by AndrewBabbitt97** [comment]
Logs & what antivirus you use are definitely a good start. Can assist as soon as I have that.

**Comment by Azrael0528** [comment]
Hi,

I use Bit defender actually. Am afk now will send the logs once am in front of the system. 

But the whole thing worked after I restarted the system. So I think we can close this issue. 

Thanks a lot for your hard work!!
