### ISSUE TITLE
Cant Control Motherboard Lights

### ISSUE THREAD

**Issue by arkad94** [AndrewBabbitt97/AuraConnect#52]
Hi! Thanks for the great app. I cant however control the motherboards lights through this, my graphic card works just fine. I have noticed that even ASUS Aura sync did not detect my motherboard lights, however the armory crate app did and does sync both motherboard and graphic card lights.

**Comment by AndrewBabbitt97** [comment]
If your MB supports Armory crate you should only have that installed, would not recommend having both Aura and Armory Crate installed. Armory Crate will install Lighting Service which is needed by my app.

**Comment by arkad94** [comment]
Thank you for the prompt reply! I did not have Aura sync installed in the current installation of windows.
I resolved the issue by going to the bios and setting only Aura lights to be on, I imagine the motherboard lights were acting as functional lights rather than Aura. Its fixed now
Thank you for this amazing implementation!
