### ISSUE TITLE
Hardcoded The Aura Vendor GUID?

### ISSUE THREAD

**Issue by chenjiancan** [AndrewBabbitt97/AuraConnect#56]
These is A great project, it works most of the time on my PC. 
My question is how to get the GUID, if I want to connect devices other  than Aura.
I found the related repo, same contributor  ChromaControl/BroadcastVendorExtractor , but no luck，no match in :
               `if (nameTest.SequenceEqual(FirstName))` 
What's the magic under?

**Comment by AndrewBabbitt97** [comment]
That tool is broken due to an update Razer made and I have no intention on fixing it.

GUIDs are assigned by Razers Dev teams.

**Comment by chenjiancan** [comment]
> That tool is broken due to an update Razer made and I have no intention on fixing it.
> 
> GUIDs are assigned by Razers Dev teams.

Thank you for your work. The current Aura GUID is working, I would try to figure a way out.
