### ISSUE TITLE
Not linking with Chroma

### ISSUE THREAD

**Issue by pappybutter** [AndrewBabbitt97/AuraConnect#57]
The program appears on synapse and was working fine but randomly stopped and is only working with Armoury Crate lighting service. I tried reinstalling both synapse and connect but it wont link back up

**Comment by AndrewBabbitt97** [comment]
Sounds related to #42

**Comment by pappybutter** [comment]
is there a fix? I didnt see one in the thread. I dont have anti virus on at all.

**Comment by pappybutter** [comment]
it shows my device is running fine on synapse as well, it doesnt say its unreachable. Also everything appears fine in armoury crate

**Comment by pappybutter** [comment]
Auraconnect is also running in task manager

**Comment by AndrewBabbitt97** [comment]
It works with ArmoryCrate correct?

**Comment by pappybutter** [comment]
It did originally but now it won’t connect. Armory crate is currently controlling the lighting from its effects

**Comment by RaidentaylorFilipeLeite85** [comment]
What appears on armory crate on Aura effects?

**Comment by RaidentaylorFilipeLeite85** [comment]
Can you put logs here?

**Comment by pappybutter** [comment]
just the regular screen and they still work like normal. How can i pull logs?

**Comment by AndrewBabbitt97** [comment]
Stale issue, but I'd recommend using latest versions of Armory Crate if still having issues.

Feel free to reopen.
