### ISSUE TITLE
AuraConnect Won't Run

### ISSUE THREAD

**Issue by Since-Atari2600** [AndrewBabbitt97/AuraConnect#60]
Not sure what to do here. I have Aura 1.06.17 (the newer version won't work on my computer.
Synapse v3
I has an ASUS ROG B450-F, running Windows 10 and have ThermalTake CPU cooler and fans that run via THeir software that has Chroma Enable. MY TT and Razer products work fine via Synapse...trying to ge my MoBo logo and LED strips to sync up.

I installed AuraConnect and it doesn't run. I manually click on the installed exe and I get a command window that opens and closes within a second or so. I was able to grab a screen shot of it.

Can you help?
![Untitled](https://user-images.githubusercontent.com/66804575/84443782-57c0e380-ac0e-11ea-8a4c-8a9abe693762.jpg)

**Comment by AndrewBabbitt97** [comment]
Your Aura/ArmoryCrate install failed to register Aura SDK components. Please reinstall it and try again.

**Comment by Since-Atari2600** [comment]
Dang, that was quick. Install which? Aura (Armoury doesn't support my board) or AuraConnect?

**Comment by Since-Atari2600** [comment]
Oh...looks like u said Aura. I'll try

**Comment by Since-Atari2600** [comment]
I uninstalled and reinstalled both Aura and AuraConnect...same error

**Comment by AndrewBabbitt97** [comment]
Might be related to a bug with Aura/Windows #42
