### ISSUE TITLE
AuraConnect not showing in Synapse

### ISSUE THREAD

**Issue by picknmixboltz** [AndrewBabbitt97/AuraConnect#61]
I installed AuraConnect and Asus Aura (also had armoury installed) but it is not showing in Synapse, do you need 1 or more Aura devices being detected for it to show up? I was planning on getting Aura Sync compatible parts and using Synapse to control them, and would like to make sure it was working before doing so, is that possible?

**Comment by GGerHbto** [comment]
I'm having similar situation, I have Aura Sync installed, aura connect instaled and razer synapse 3 installed, not sure if I should do anything else.. Which information would be usefull to share to troubleshoot the issue?

**Comment by AndrewBabbitt97** [comment]
Logs from C:\ProgramData\AuraConnect\logs are useful.

Keep in mind I am transitioning to a new PC build around the Maximus XII Formula here soon, and haven't had a ton of time to troubleshoot why ArmoryCrate isn't even working on my own system right now.

You can rest assured that that AuraConnect even if it's not fully working when you build a PC focused aroun Aura parts that I will get it working again as I use it myself for my own system.

Most issues lately have stemmed from issues with Aura itself along with some recent Windows updates. At some point I may be cutting off support for certain versions of Windows and Aura. But if you build something focused around Aura you should be good for Synapse connectivity.

I'm planning on looking at

**Comment by tlewis17** [comment]
I pulled down the source and figured out the cause. I've never had Aura set up prior to today. And I've only ever had ArmouryCrate. The AuraSDK is no longer installed as a COM+ onto the system through ArmouryCrate. So the initialization is forever stuck in a loop in the AuraProvider of your RGBKit. I changed the COM+ reference to the direct AuraSDK x64 DLL that was installed by ArmouryCrate, commented out the looping health check for the COM+ and now it works for me. I just used my custom build and put it in the service directly and all is well.

**Comment by AndrewBabbitt97** [comment]
....

AuraSDK hasn't been used in quite a while, and I can confirm the latest builds of ArmoryCrate are using COM with the latest version of ArmoryCrate even on Z490 that was just released. Missing COM reference was a recent Windows + Aura issue where AURA wasn't registering COM objects correctly and failing.

You shouldn't ever need to touch the code to get this working, and the latest build works fine so long as you don't run into that bug in Aura. (Make sure you are on the latest Windows 29 build 2004 and latest Windows updates)

**Comment by tlewis17** [comment]
Maybe so, but then you'd have to explain why this process doesn't exist yet ArmoryCrate is able to control lights for my DRAM and Keyboard Rog Strix) just fine.

``` csharp
    var comServiceRunning = Process.GetProcessesByName("atkexComSvc").Length != 0;
```    
I'll do some more digging since I can reproduce the problem.

**Comment by tlewis17** [comment]
Oh actually I know exactly what the problem probably is. Armory Crate is used for Aura supported devices such as the DRAM and keyboard, however, my motherboard is an MSI which uses MysticLight and goes through a different process. Therefore I don't actually have asus motherboard software installed.

**Comment by AndrewBabbitt97** [comment]
We don't support keyboards. We also don't support laptops. Anything outside of ASUS Motherboards and RGB headers on those Motherboards are not guaranteed to work.

We won't ever purposefully block other devices, but if a device doesnt get exposed in the same way a motherboard does in Aura SDK then it won't work.
