### ISSUE TITLE
One device no longer working with aura connect

### ISSUE THREAD

**Issue by pappybutter** [AndrewBabbitt97/AuraConnect#62]
I recently did a clean windows reinstall and i was able to get my asus devices connect to chroma. After awhile only my ram gets recognized while my motherboard only does armory crate effects.

**Comment by AndrewBabbitt97** [comment]
Need logs from C:\ProgramData\AuraConnect\logs

**Comment by pappybutter** [comment]
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4854371/AuraConnect.log)

**Comment by pappybutter** [comment]
It is no longer in task manager processes when I start my computer

**Comment by AndrewBabbitt97** [comment]
If only one device doesn't get taken over by Synapse the issue is Aura/Armory Crate related.
