### ISSUE TITLE
Aura connected with Synapse but do nothing

### ISSUE THREAD

**Issue by crscaballero** [AndrewBabbitt97/AuraConnect#63]
I've already installed Armoury Crate last version, updated everything, use Aura to change light and be sure that is working and sync, and then I've installed Aura Connect, reboot my PC, I can see the Aura icon into Razer Synapse, I see the icon light changing into Synapse, but my aura device are not doing anything , I've unistalled and reinstalled everything, no changes, I've removed by antivirus (I'm using Malwarebyte), and even before use it, with just Windows Defender I was having exactly same problem, just no more ideas what else I can do

I'm, using a motherboard ASUS ROG Strix Z490-G with an Intel I7 processor 

not sure what other info I can give you

thanks in advance

**Comment by AndrewBabbitt97** [comment]
I'm gonna be a bit slower on things right now relating to AuraConnect.

I myself am moving to Z490 with a Maximus XII Formula, and currently my ArmoryCrate is non functional on my Maximus XI Formula and haven't had time to look at it.

I am looking at rewriting a part of AuraConnect to potentially increase performance as well, so I'll be looking at several things soon.

**Comment by crscaballero** [comment]
Thank you so much for your quick response, and of course the work that you have done so far, if I can help you with some test or something just let me know, I'm mostly web developer, but with some orientation maybe I could help you

**Comment by AndrewBabbitt97** [comment]
Are you still having issues?

I know latest versions have been working solid for me.

**Comment by crscaballero** [comment]
Seems to be working fine, thank you!
