### ISSUE TITLE
prise en charge nouveau périphérique asus ROG CHAKRAM

### ISSUE THREAD

**Issue by Hotpepere** [AndrewBabbitt97/AuraConnect#65]
Bonjour
Je post au cas ou car coté asus ils ne trouvent pas le problème et je ne pense pas que cela vienne de aura connect mais on ne sait jamais
problème identifié:
sous chroma studio/starlight au redémarrage pc tout est bien géré par chroma<->auraconnect<->asus aura
mais aléatoirement les lumières se figent et le seul moyen pour régler le soucis est de redémarrer le pc et de débrancher le dongle RF de la souris  une fois le système démarre je rebranche le dongle et pas de prise en compte de la souris et donc tout va bien.Mais si la souris se retrouve a être géré par chroma sa bug
idem dans un jeux via chroma vizualizer la c'est auraconnect qui se ferme et l’éclairage qui se fige, obligé de modifié le service de auraconnect pour un redémarrage automatique 
je peux poster les logs si nécessaire
merci
motherboard :asus maximus IX code
GPU:asus rog 1070Ti strix
razer tartarus V2
G-skill trident Z RGB
asus rog chakram

**Comment by AndrewBabbitt97** [comment]
Don't speak French myself (I'm actually Japanese) but if you can post logs that would be great.

Also AuraConnect does not support hot reloading devices, they must be plugged in when AuraConnect starts to work.

**Comment by Hotpepere** [comment]
first of all thank you for your responsivenessI noticed that aura connect did not take hot new peripherals. It is for this reason that I wait until Windows has started to connect the mouse as it is not supported and all the other peripherals can be managed without problem. I forgot to specify that everything was frankly reinstall and several versions of asus aura were tested without success as well as firmware and mouse driverSofutō~ea wa subarashīdesu anata no shigoto o arigatōProvenance : Courrier pour Windows 10 De : Andrew BabbittEnvoyé le :mardi 30 juin 2020 17:07À : AndrewBabbitt97/AuraConnectCc : Hotpepere; AuthorObjet :Re: [AndrewBabbitt97/AuraConnect] prise en charge nouveau périphérique asus ROG CHAKRAM (#65) Don't speak French myself (I'm actually Japanese) but if you can post logs that would be great.Also AuraConnect does not support hot reloading devices, they must be plugged in when AuraConnect starts to work.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  
	
      
		Garanti sans virus. www.avast.com

**Comment by AndrewBabbitt97** [comment]
Will need logs from C:\ProgramData\AuraConnect\logs

You must use the latest version of Aura, I don't support tickets not using the latest version. Also I don't believe I know of anyone who has used peripherals with AuraConnect. My most supported configuration is Motherboard + RGB headers and GPUs. So pretty much just things inside the chassis.

**Comment by AndrewBabbitt97** [comment]
Also it looks like you may be required to use ArmoryCrate for that device, the drivers page does not provide any Aura version for your mouse. You are supposed to use ArmoryCrate as it has the appropriate HALs to be able to control your mouse.
