### ISSUE TITLE
Lighting works on asus motherboard and graphics card but not RGB header

### ISSUE THREAD

**Issue by Wizkid288** [AndrewBabbitt97/AuraConnect#66]
I can control the lights on my motherboard and on my graphics card but not my RGB (not serial) strip. Is this normal?

**Comment by AndrewBabbitt97** [comment]
Need log file upload from C:\ProgramData\AuraConnect\logs

**Comment by Wizkid288** [comment]
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4859312/AuraConnect.log)

**Comment by AndrewBabbitt97** [comment]
When you refer to RGB strips, did you mean Addressable or non-addressable?

If it's addressable I personally haven't ever tested them, but I have things coming in soon for that. I know non addressable strips work fine.

**Comment by Wizkid288** [comment]
non-addressable strips

**Comment by AndrewBabbitt97** [comment]
What is the motherboard model?

**Comment by Wizkid288** [comment]
asus e gaming z390

**Comment by AndrewBabbitt97** [comment]
Forgot to comment on this.

This issue is Aura related with it not exposing that header. Nothing I can do about that.
