### ISSUE TITLE
Aura Connect Not Changing Keyboard Color

### ISSUE THREAD

**Issue by Brickfalcon** [AndrewBabbitt97/AuraConnect#67]
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4872989/AuraConnect.log)
Shows up in synapse but doesn't change the keyboard color.

**Comment by AndrewBabbitt97** [comment]
1. Aura Connect logs show that the Aura SDK isn't picking up any devices you may have, what are the Aura devices that you have? I believe this may be down to incompatibility, it looks like whatever you have can't be used with the SDK.

2. AuraConnect shows frequent disconnects, this is usually seen when another software is interfering with the connectivity (antivirus in particular Kaspersky causes this) or restarting of Synapse frequently.

**Comment by Brickfalcon** [comment]
I have a ASUS A15 and the laptop keyboard is RGB. The only security is windows defender.

**Comment by AndrewBabbitt97** [comment]
Would consider reinstalling ArmoryCrate, Synapse, and AuraConnect. If it still doesn't work I think it's safe to say regardless that if your laptop doesn't show up in the list that they aren't supported.

Bear in mind, AuraConnect was heavily designed with desktop components in mind meaning Motherboards and the Aura headers on them. I would hate to imagine the experience on a keyboard given that Synapse only gives us 5 led colors to apply to a device at a given time, meaning that a keyboard would only be able to have up to 5 colors across all keys at any point.

**Comment by AndrewBabbitt97** [comment]
FYSA: If it doesn't work, there's nothing I can do to add support. It is a limitation of the Aura SDK that ASUS provides not AuraConnect.

**Comment by Brickfalcon** [comment]
I tried reinstalling all 3 and restarting my laptop and it didn’t work so I think it’s unsupported. Thanks for the help
