### ISSUE TITLE
Very high CPU utilisation

### ISSUE THREAD

**Issue by mattmoo** [AndrewBabbitt97/AuraConnect#68]
This seems to use a lot of CPU on my machine (~75% on i5-7600k). Is that working as intended? Not sure what further to do to diagnose.

**Comment by AndrewBabbitt97** [comment]
Check #8 if using something aside from non-static effects you WILL experience CPU usage increases. Especially noticable on older CPUs.

Am planning some performance focused updates soon, but these are mostly focused on improving the lag of effects but it may also reduce CPU usage but cannot confirm right now.

**Comment by mattmoo** [comment]
Ah yes, fair enough. Aura does seem pretty poorly optimised.
