### ISSUE TITLE
doesn't work with ROG laptop (keyboard)

### ISSUE THREAD

**Issue by raissatito** [AndrewBabbitt97/AuraConnect#69]
i have ROG Laptop with RGB Keyboard and Razer mouse. when i installed AuraConnect, nothing showed up in razer synapse. i read some youtube comments a few days ago and someone is also having same issues and you told him to write an issue here. thanks

**Comment by AndrewBabbitt97** [comment]
Have you gone through all of the troubleshooting steps in the readme? https://github.com/AndrewBabbitt97/AuraConnect

Also even if you do get it to show up in Synapse, I just had someone report that their ASUS laptop doesn't work, it doesn't show up in the Aura SDK so it can't be controlled through Synapse: #67
