### ISSUE TITLE
No Support for Asus Z390-E?

### ISSUE THREAD

**Issue by Justin-Lund** [AndrewBabbitt97/AuraConnect#7]
I have an Asus Z390-E motherboard and it doesn't light up/sync with chroma. My other Asus gear (GPU + CPU cooler) are working great. Would love to have that up and working!

Love what you're doing here, thank you so much!

**Comment by AndrewBabbitt97** [comment]
Might I ask how your CPU cooler is hooked up?

I'm guessing it works using an RGB header? If so what type? 3 or 4 pin?

**Comment by Justin-Lund** [comment]
It's the ASUS ROG RYUO 240
It's a bit of an interesting case, it connects via Micro USB into the AIO cooler, and then goes to a 9-pin USB 2.0 connector on the MoBo.
The unusual connector is because it has a screen on it.

**Comment by AndrewBabbitt97** [comment]
What version of AURA are you using?

**Comment by Justin-Lund** [comment]
1.07.71

**Comment by Justin-Lund** [comment]
Hey - just fired up Aura and got it worked! I just realized that it was defaulting to static - once I hit "Select Effect" at the bottom - it synced up. I didn't really think about touching Aura because the other components just started working right off the bat, so I figured it was all automated.

My bad - but might be worth adding a quick note about that to the ReadMe!

**Comment by AndrewBabbitt97** [comment]
That's odd, only the lighting service is needed for this to work. Sounds like it was something wrong with your specific install that was preventing it from working. This is the only case I have seen with this, if i see more I'll investigate it more.
