### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by KingDavid204** [AndrewBabbitt97/AuraConnect#71]
Line 18:
No files found matching "D:\AURA Connect\AuraConnect-master/src\AuraConnect.Setup\..\bin\Release\netcoreapp3.1\win-x86\publish\**

I already installed the net core app from Microsoft. And if this isn't the correct way to open the file, please specify the direction, I can't open the file without a third party software. The one I tried with is Inno Setup Compiler 6.0.5. Thanks in advance.

**Comment by AndrewBabbitt97** [comment]
You need to publish a release from Visual Studio which will create the files to be used by Inno Setup. Eventually Inno will be going in favor of MSIX which will be build from Visual Studio as well.

**Comment by AndrewBabbitt97** [comment]
You can also use build.bat in the source code folder to do a full build, it's set up to generate a setup file for you as long as you have Inno installed and the .NET Core 3.1 SDK

**Comment by KingDavid204** [comment]
Oh okay thanks

**Comment by KingDavid204** [comment]
I appreciate the fast response
