### ISSUE TITLE
Asus z390-e Armoury Crate not working

### ISSUE THREAD

**Issue by Anita-Hanjaab** [AndrewBabbitt97/AuraConnect#72]
Hi there,

I tried your software with Aura Sync, the mother board light would freeze but everything else syncs. When I changed to armoury crate, nothing syncs with Synapse. I made sure Auraconnect is running and everything is on the latest version. The software detects all my products but nothing happens. It's still syncing to armoury crate settings. Love your work, hopefully there's a fix for this. Thanks!

info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Program Files (x86)\ASUS\AURACONNECT
info: AuraConnect.Worker[0]
      Initializing Aura Connect...
Check DRAM Module. (1)
info: AuraConnect.Worker[0]
      Found Device: AURA - Corsair Vengeance RGB Pro - 40 Lights
info: AuraConnect.Worker[0]
      Found Device: AURA - Vga 1 - 1 Lights
info: AuraConnect.Worker[0]
      Found Device: AURA - RYUJIN 1 - 5 Lights
info: AuraConnect.Worker[0]
      Found Device: AURA - Mainboard_Master - 5 Lights
info: AuraConnect.Worker[0]
      Found Device: AURA - AddressableStrip 1 - 120 Lights
info: AuraConnect.Worker[0]
      Aura Connect started successfully!
info: AuraConnect.Worker[0]
      Razer Chroma Broadcast API connected
info: AuraConnect.Worker[0]
      Razer Chroma Broadcast API disconnected
info: AuraConnect.Worker[0]
      Razer Chroma Broadcast API connected
info: AuraConnect.Worker[0]
      Razer Chroma Broadcast API disconnected
info: AuraConnect.Worker[0]
      Razer Chroma Broadcast API connected

**Comment by AndrewBabbitt97** [comment]
I need the date/time stamps on these logs to have more context as to what's going on.
