### ISSUE TITLE
On startup, Asus devices sync up only with some Razer devices

### ISSUE THREAD

**Issue by tihomirbz** [AndrewBabbitt97/AuraConnect#73]
I've got a Razer mouse, keyboard and mousepad. I've set up Synapse on spectrum cycling and the devices are normally all synced.

With Aura Connect enabled however, on startup, the Asus devices pick up one colour, together with 1 or 2 of the Razer devices, while the rest of the Razer devices pick up another colour.

If I go in Synapse and use the button to sync the colour scheme, it corrects it and now all devices, both Razer and Asus, have the same colour. The bug happens only after startup.

All devices are set up to use spectrum cycling, but for some reason when the service loads initially, it gets mixed up and doesn't sync them all properly.

**Comment by AndrewBabbitt97** [comment]
Sounds like a Synapse bug and not an AuraConnect bug. Please report this to Razer.

To try and fix it for yourself, would recommend reinstalling all Razer software and trying again.
