### ISSUE TITLE
Cant find AuraConnect in Razer Synapse device list

### ISSUE THREAD

**Issue by chandlerlucius** [AndrewBabbitt97/AuraConnect#74]
First off, awesome work Andrew, I love seeing cool projects like this.

I cannot seem to find AuraConnect in the device list, am I doing something wrong? I am trying to sync with an Asus STRIX-RX580 graphics card. The logs make me think something is stopping it from initializing, you can view them in the screenshot.

Thanks in advance!

I have attached a screenshot and have tried the following:
1.   Installed most recent windows build 19041
2.   Installed AMD Adrenalin and latest RX580 drivers
3.   Installed Razer Synapse and latest Razer drivers
4.   Installed Asus Armoury Crate
5.   Installed AuraConnect
6.   Connected Mice and Keyboard to computer and verified control with Razer Synapse
7.   Connected GPU with computer and verified control with Aura Sync
8.   Made sure AuraConnect is running as Process and Service
9.   Added exclusions to Windows Defender
10. Allowed Aura Connect through Windows Firewall
11. Restarted PC
12. Connected to Private home network

![image](https://user-images.githubusercontent.com/17418781/87863413-56c35600-c920-11ea-9491-c93fdccf8099.png)

**Comment by AndrewBabbitt97** [comment]
What I'm seeing is that it's stuck on Aura SDK initialization, looks like the call to Aura is stalling. I'd consider doing a clean install of Aura/ArmoryCrate.

I will have more detailed logs in an upcoming rewrite.

Please also ensure the following processes are running: "LightingService" and "atkexComSvc"

**Comment by DjTj1539** [comment]
I'm having this same problem, but atkexComSvc isn't running and I can't find it downloaded. I can barely find information about this service. Only websites about how it's bad and how to uninstall it.

**Comment by AndrewBabbitt97** [comment]
So this may have changed with armory crate on that service, Armory Crate may only install it if you are using an ASUS motherboard but I have no idea when/why this service is installed by ASUS. I'n the past It looked like there was a dependency between the two services so I put in a check for both of them.

I am currently not able to investigate this (dog sitting for family until mid next week, and won't be near my desktop until then). Ill evaluate this over again and see.

**Comment by chandlerlucius** [comment]
Thanks man! I am getting an Asus Motherboard this weekend and will be reinstalling everything. So I will let you know if having the Asus Motherboard fixes the issue.

Appreciate the quick feedback, keep up the good work!

**Comment by ThatsTheJoke** [comment]
Hey,

I just bumped into this thread and I'm finding the same exact issue with a ROG Strix X570-E motherboard, just did a fresh reformat. AuraConnect was working with Aura Sync but I was getting some stuttering issues with the effects so I wanted to try and see if using Armoury Crate would fix it, but like I said literally the same issue as OP in regards of Synapse not picking up the service.

**Comment by AndrewBabbitt97** [comment]
Yeah it might be the service not existing in some cases, haven't had time to look into it yet due to work and life getting in the way. I'll try to see about doing a test version for people to try in this thread this week and see if that works for you guys. If so I'll push out a new version with the change.

**Comment by ThatsTheJoke** [comment]
No rush man, though amusingly enough out of the blue it managed to hook into Synapse, though it wasn't changing color settings. Then a couple restarts/toying around with Armoury Crate it finally went into stand by mode and I have control over the settings via Synapse again, that being that the effects stuttering that I mentioned is still there, every 5 seconds it seems to just skip and it doesn't do it with native control via Armoury Crate's effects.

**Comment by AndrewBabbitt97** [comment]
What ASUS devices do you have?

**Comment by ThatsTheJoke** [comment]
> What ASUS devices do you have?

Only ASUS product I have is the x570-E motherboard, latest bios is installed for whatever that's worth.

**Comment by AndrewBabbitt97** [comment]
> > What ASUS devices do you have?
> 
> Only ASUS product I have is the x570-E motherboard, latest bios is installed for whatever that's worth.

Need logs from C:\ProgramData\AuraConnect\logs

**Comment by ThatsTheJoke** [comment]
[AuraConnect.zip](https://github.com/AndrewBabbitt97/AuraConnect/files/5478625/AuraConnect.zip)
Sorry for the delay, just got back from a trip.

**Comment by AndrewBabbitt97** [comment]
AuraConnect has been archived, please move onto the replacement ChromaControl: https://github.com/ChromaControl/ChromaControl
