### ISSUE TITLE
leds light up in wrong order

### ISSUE THREAD

**Issue by REACHER217** [AndrewBabbitt97/AuraConnect#75]
i have a rog strix b450-f gaming and a rog strix rtx2060super, both of these work well enough with aura connect, but i also have adata xpg d41 rgb ram , and adata xpg s40g rgb m.2 ssd , and both of these light up the leds in wrong order which breaks any lighting pattern 
or the ram , the light pattern starts from the second led for both ram modules and the ssd 
i do have a wraith prism cpu also controlled by synapse and i can notice the aura connect is a bit laggy compared to the fan which isnt a big deal 
but i hope you can fix the ram and ssd sync issues 
thnx for this wonderful project

**Comment by AndrewBabbitt97** [comment]
Video would be helpful here, but even then I can't promise a fix for this. I don't get the model number for ram/RGB headers. I may be able to implement a fix in the future with the upcoming rewrite to account for specific hardware, but until then nothing.

**Comment by apocolipse** [comment]
@AndrewBabbitt97 
![AF63932F-FB60-482C-9786-0E3FEFE67188](https://user-images.githubusercontent.com/260871/88723042-318bd000-d0f6-11ea-925d-687aa6742cae.jpeg)
Here’s an example, I’m using an Asus z490 rog Maximus xii hero with addressable RGB headers, the side glass leds on the right are built into the case and controlled by Synapse already, clean rainbow wave effect, same effect on the strip in the bottom of the case, and you can see it’s not addressing them right (red leds should be grouped together).  Armory crate can achieve the same effect properly with its built in rainbow effect, but chroma studio can’t seem to address them in the right order.

**Comment by AndrewBabbitt97** [comment]
No, it's in the right order. It's that it can only technically address 5 (or 4, I forget atm) LEDs. That's all Synapse gives us, if you look at the bubble in Chroma Studio you can see dots for Asus. Those dots are the colors being passed for us to use. We have to use those colors for all ASUS LEDs. This is a limitation of Synapse.
