### ISSUE TITLE
Doesnt Show Multi Device [RAM, MOBO, 5V, etc]

### ISSUE THREAD

**Issue by Wontell** [AndrewBabbitt97/AuraConnect#76]
Hello,
As of right now I managed to get the ASUS circle in my CHROMA program and to control it, but it controls everything connected to the motherboard as single device, is tehre a way to split it? Do you plan it as Future Feature or maybe its already implemented and I dont see it?

G.SKILL RAM shows as separate entity in iCUE and ASUS armory, but trough Chroma it part of the motherboard.
Same with both 5V DRGB connections.

Any plans to allow separate control? At least minimal like RAM.

Regards

**Comment by AndrewBabbitt97** [comment]
It's a limitation of Synapse, I have been working with their dev team to try and get better control over devices. I have nothing to announce on this front at the moment.

Right now all devices are controlled as a single bubble in Synapse with a set of 5 shared LEDs.

That is the maximum amount of control that Synapse allows me to have, and I am not able to add more. If I were I would have already done it :)

**Comment by Wontell** [comment]
> 
> 
> It's a limitation of Synapse, I have been working with their dev team to try and get better control over devices. I have nothing to announce on this front at the moment.
> 
> Right now all devices are controlled as a single bubble in Synapse with a set of 5 shared LEDs.
> 
> That is the maximum amount of control that Synapse allows me to have, and I am not able to add more. If I were I would have already done it :)

Hello.
If not control, Is there a way to disable a device maybe? for example G.Skill RAM has their own soft and it has option to sync with Chroma, so now its a huge mixup, when I change ASUS bubble it also changes RAM, but RAM has its own Bubble.

What do you mean 5 shared LEDS? All I see a bubble and thats it, the bubble has some circles inside but they do part of the bubble and unclickable

**Comment by KyleStilkey** [comment]
> > It's a limitation of Synapse, I have been working with their dev team to try and get better control over devices. I have nothing to announce on this front at the moment.
> > Right now all devices are controlled as a single bubble in Synapse with a set of 5 shared LEDs.
> > That is the maximum amount of control that Synapse allows me to have, and I am not able to add more. If I were I would have already done it :)
> 
> Hello.
> If not control, Is there a way to disable a device maybe? for example G.Skill RAM has their own soft and it has option to sync with Chroma, so now its a huge mixup, when I change ASUS bubble it also changes RAM, but RAM has its own Bubble.
> 
> What do you mean 5 shared LEDS? All I see a bubble and thats it, the bubble has some circles inside but they do part of the bubble and unclickable

I did not know myself that G.Skill finally added Chroma ability to their RAM software, but yes it seems as if AuraConnect is taking over control of the RAM. Disabling/Unlinking the G.Skill RAM from Aura or Armoury doesn't remove resolve this. Possibly it's not checking anything and is just whatever devices are showing up with Aura is just being controlled, not 100% sure but anything you have for us to try would be awesome. Thanks!

**Comment by AndrewBabbitt97** [comment]
The circles inside the bubble are the LED colors, the number of those inside the bubble are all the colors Synapse sends to AuraConnect at a time and that's it.

We have no way to exclude specific devices from control in the Aura SDK. It's an all in or all out experience. You would have to unlink the gskill memory from Aura for it to not be controlled.
