### ISSUE TITLE
Aura Sync not showing in Razer synapse

### ISSUE THREAD

**Issue by ZeniSkywalker** [AndrewBabbitt97/AuraConnect#77]
I already had razer synapse installed, just downloaded and installed auraconnect. Restarted the computer and nothing. What can I do?
![image](https://user-images.githubusercontent.com/20309379/89116871-3ee6e880-d46f-11ea-8b2c-8abba48ab5d0.png)
![image](https://user-images.githubusercontent.com/20309379/89116893-7190e100-d46f-11ea-84fa-bb7c3b4818a8.png)

**Comment by creampie95** [comment]
I have same problem
![2020 08 04-12 17](https://user-images.githubusercontent.com/17644280/89249215-a5752d80-d64c-11ea-9775-58d65748eaf7.png)

**Comment by AndrewBabbitt97** [comment]
Probably related to #74
