### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by MrMaik7** [AndrewBabbitt97/AuraConnect#8]
Is it normal that the application takes up to 30% of my  CPU Usage (wich leads to Stuttering in games in my case) 
im Running a i5 6600k 
![Taskmngr](https://user-images.githubusercontent.com/56392030/67458317-2de28e80-f636-11e9-8647-917c2f6fd529.PNG)
Don´t focus on AIDA64 im just testing if my temps are a problem too.

**Comment by AndrewBabbitt97** [comment]
I see max of 7% when running the fire effect, if under static color its 0/0.1%. I am however on a 9900K

What effect are you using?

**Comment by AndrewBabbitt97** [comment]
Ill have to do some perf monitoring, non static effects will always use a lot more CPU there's not much we can do about this.

When you have a static color, an update is sent once every few seconds from Synapse.

When its an effect like wave/fire updates are sent hundreds of times every second. This increases CPU usage significantly.

Ill see if there's anything I can do but I'm not sure if there is.

**Comment by AndrewBabbitt97** [comment]
New release is out, please test this new release and let me know how things are in it:

https://github.com/AndrewBabbitt97/AuraConnect/releases/tag/1.0.1
