### ISSUE TITLE
Something Cool I found out, Not an issue.

### ISSUE THREAD

**Issue by sledgep** [AndrewBabbitt97/AuraConnect#80]
So I have the GSkill RGB RAM, now I disconnected the RAM from Asus Aura, and installed installed the GSkill RGB Software, the cool thing is this.  not only can I control just the RAM using the GSkill software, but I can link the GSkill software to Razer Chroma, and have it run independently.  

Just thought I would share that, hoping to see a feature, were we can disable Asus Aura Devices from Aura Connect, so they can be run from Aura if we want them too, for example Addressable RGB Strips.

Thank you

**Comment by AndrewBabbitt97** [comment]
You can't disable select devices with the Aura SDK, it's all in or all out.

My recommendation is to just not use the G.Skill software and control ram through Aura which works with my software anyways.
