### ISSUE TITLE
Bug Report: Connecting/Disconnecting USB Device Briefly Interrupts Lighting

### ISSUE THREAD

**Issue by tark95** [AndrewBabbitt97/AuraConnect#81]
Armoury Crate suddenly stopped recognizing all the non-Razer gear in my PC a few days ago and which made me try out the regular Aura software. Everything started working again after that but now every time I plug in a USB device or turn on my Bluetooth controller (and vice versa) all the Asus lighting turns off for a few seconds before going back to normal.
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/5267673/AuraConnect.log)

**Comment by AndrewBabbitt97** [comment]
This is what Synapse does when a new device is plugged in. Nothing unusual about this.
