### ISSUE TITLE
Asus ROG Strix Scar 17 

### ISSUE THREAD

**Issue by Pr12m** [AndrewBabbitt97/AuraConnect#82]
Hello everyone,
i hope this request is in the right area.

I try to connect Razer Synapse with Aura center from the Asus Rog.
I download the auraconnect, but i can`t see the aura in synapse.

Is it because it doesn't work with laptop or do I need some software for laptop and its internal RGB connections 

Rgds 

Prizm

**Comment by AndrewBabbitt97** [comment]
Laptops/keyboards are flat out not supported. It's just not something that makes sense with how Synapse provides us colors to use.
