### ISSUE TITLE
Lights freezing when opening Chroma games

### ISSUE THREAD

**Issue by Jwilliee** [AndrewBabbitt97/AuraConnect#85]
Hello, this was working perfectly but recently I installed a new desk and unplugged my pc, when I booted it back up and set aura and synapse up all my profiles worked just like they did before but now when I go into a game my motherboard/led strips freeze, but my mouse and keyboard lights work fine, any idea if I'm just missing something in setup? I uninstalled and reinstalled synapse and aura a few times now and can't figure it out D:

**Comment by AndrewBabbitt97** [comment]
Does this game have anti-cheat? If so it may be blocking the connection. Nothing I can do if this is the case, have reached out to the developers of anti-cheat software and never get useful responses from them.

**Comment by Jwilliee** [comment]
It does have anti-cheat but it was working yesterday before I unplugged my computer :/

**Comment by Jwilliee** [comment]
Thanks for such fast response btw!

**Comment by AndrewBabbitt97** [comment]
Which anti-cheat software is it? I have also seen sporadic results with them

**Comment by Jwilliee** [comment]
easy anti cheat, and warden (I think thats what overwatch uses)

**Comment by TheGhostie21** [comment]
> Hello, this was working perfectly but recently I installed a new desk and unplugged my pc, when I booted it back up and set aura and synapse up all my profiles worked just like they did before but now when I go into a game my motherboard/led strips freeze, but my mouse and keyboard lights work fine, any idea if I'm just missing something in the setup? I uninstalled and reinstalled synapse and aura a few times now and can't figure it out D:

Can confirm having the same issue after Synapse update. Tried this on other games with Chroma enabled like "Tera", lights would freeze entirely unless if your turn off lighting effects on connect settings with only my Deathadder v2, syncing to the game profile. Tried clean install both Synapse and ASUS connect, the same issue. RGB only syncs with normal Chroma effects, only games that supported by Chroma Workshop seem affected.

**Comment by gothaussen** [comment]
> > Hello, this was working perfectly but recently I installed a new desk and unplugged my pc, when I booted it back up and set aura and synapse up all my profiles worked just like they did before but now when I go into a game my motherboard/led strips freeze, but my mouse and keyboard lights work fine, any idea if I'm just missing something in the setup? I uninstalled and reinstalled synapse and aura a few times now and can't figure it out D:
> 
> Can confirm having the same issue after Synapse update. Tried this on other games with Chroma enabled like "Tera", lights would freeze entirely unless if your turn off lighting effects on connect settings with only my Deathadder v2, syncing to the game profile. Tried clean install both Synapse and ASUS connect, the same issue. RGB only syncs with normal Chroma effects, only games that supported by Chroma Workshop seem affected.

I confirm what the friend says above. I updated the version of synapse and the chroma stopped working with the games or the visualizer. only works with normal effects.

**Comment by TheGhostie21** [comment]
Wanted to add a bit more info, I've disabled "System Watcher" (since that know to cause conflicts it seems), disabled anti-virus, the same issue still arises, at least that removes the antivirus out of the process of elimination.

**Comment by TheGhostie21** [comment]
Hi,

wanted to make an update on the issue:

I've done a few things:

- clean install of windows (USB Method with newest October update)
- have not installed Kaspersky (to make sure it's not the culprit) 
- reinstalled Asus ARMORY (comes with the motherboard upon installing windows)
- reinstalled Razer Synapse and Asus Connect 

I'm currently using an ASUS STRIX X570-E motherboard, makes me wonder if this cause is due to syncing issues? At this point, I'm not even sure. Everything except Chroma Apps/workshop works. Something must have broken after the razer update? I know the developer isn't having any of these issues, only seems it affecting certain users. what type of motherboards you guys have? Just make sure this isn't an ASUS issue or who knows what causes it?

**Comment by AndrewBabbitt97** [comment]
This is a Synapse issue, Synapse isn't sending signals when using visualizer/games.

There's nothing I can do about this besides wait for an update from Razer.

**Comment by AndrewBabbitt97** [comment]
Also moving this topic to #89 to keep things together.
