### ISSUE TITLE
The AuraConnect problem with Visualizer

### ISSUE THREAD

**Issue by MoSoooo** [AndrewBabbitt97/AuraConnect#86]
Hi Buddy, First. Thank you :) amazing app.

Since last Razer Synapse update The Asus parts don't work with Visualiser and Wallpaper Engine like before.

Please help.

Thank you

**Comment by AndrewBabbitt97** [comment]
I don't get any info on visualizer using Razers SDK.

If a Synapse update breaks visualizer, you will have to wait on an update to Synapse for a fix for that. There's nothing I can do on my side to fix this. Same goes for Wallpaper Engine. They both work in the same WAY AFAIK. Sounds like Razer broke something in Chroma.

**Comment by MoSoooo** [comment]
Even if it works fine with my Razer products? so keyboard etc working fine, just the mobo lights in case?

**Comment by MoSoooo** [comment]
Not sure if this comes through..just thought Id mention visualizer works on my keyboard just not with asus connect..sighOn 07 Oct 2020 01:32, Andrew Babbitt <notifications@github.com> wrote:
I don't get any info on visualizer using Razers SDK.
If a Synapse update breaks visualizer, you will have to wait on an update to Synapse for a fix for that. There's nothing I can do on my side to fix this. Same goes for Wallpaper Engine. They both work in the same WAY AFAIK. Sounds like Razer broke something in Chroma.

**Comment by AndrewBabbitt97** [comment]
Yeah, that doesn't change anything. It's still something on Razers side unfortunately.

There's nothing I can do, sorry 🙃
