### ISSUE TITLE
Significant delay with RGB effects

### ISSUE THREAD

**Issue by The-Mighty-Spoon** [AndrewBabbitt97/AuraConnect#88]
There is a noticeable delay with the Lighting effects compared to the razer chroma peripherals.
It's especially noticeable if I use the audio meeter lighting effect in Razer Synapse 3.

Is there a possible fix for this out there?

**Comment by AndrewBabbitt97** [comment]
No, this is a known issue.

This may get better here soon, rewriting the core lighting loop in c++ to increase performance. This may or may not help. Anything beyond that is delays in the Aura SDK or Synapse
