### ISSUE TITLE
solid color or bust

### ISSUE THREAD

**Issue by Rylleyryelle** [AndrewBabbitt97/AuraConnect#9]
currently i don't see any way to edit LEDs or even LED groups individually.
On the display, I see 4 spots that light up and can only control them all at once.
spots 1-4 control the LEDs on my Corsair DIMMs in a strange, not quite top to bottom manner while spot 3 also controls my CPU fan and motherboard lighting on the ASUS ROG.

I realize this is a work in progress so less of a complaint and more of a feature request for the future

**Comment by AndrewBabbitt97** [comment]
You can't control them individually, this is actually a limitation on Razer Synapse not this program.

Razer sends AuraConnect the 4 LED colors and we have to use those colors across all devices and that's it.

I could implement different algorithms for the way the 4 colors are distributed but that's about it, I have experimented with this a lot actually and ended on this combination after doing other ways due to it being similar to the way other OEMs were doing it to keep it matching if people were using other Connected Device Program devices.

**Comment by Rylleyryelle** [comment]
is there no way to separate those 4 groups? It'd be nice to be able to create manual rainbowing on the DIMMs instead of pretending an 8-LED DIMM that's getting color info in groups of 2 is a 1-LED unless I use the Starlight effect

**Comment by AndrewBabbitt97** [comment]
No, there's not. Synapse creates the one item in studio for all devices controlled by a single manufacturer. We cannot split them or control them ourselves. I have talked to Razers team about this already.

So at this time I have to distribute 4 LEDs worth of color across all LEDs from ASUS that you have. Not the most ideal solution but that's just how it is.

**Comment by Rylleyryelle** [comment]
Well that's unfortunate. Thanks for at least trying tho!

**Comment by AndrewBabbitt97** [comment]
Yeah, I can see about ordering the LEDs differently through a different algorithm for the LEDs but we're still stuck with just 4 colors at a time across all LEDs.

If you have any other feedback feel free to let me know.

**Comment by Rylleyryelle** [comment]
that might mess up other peoples setups, but i know from my experience,
[1][2][3][4]
controls
DIMMs: (top) [1][2][3][4][1][2][3][4] (bottom)
CPU Fan: [3]
Motherboard: [3][3][3][3]

Corsair Vengeance RGB
Wraith PRISM
ASUS ROG STRIX B450-F

**Comment by AndrewBabbitt97** [comment]
I think I'm gonna make a device info tool to gather some info to look into your lights more.

What RGB header does the CPU fan use? 3 or 4 pin?

**Comment by Rylleyryelle** [comment]
4 pin vRGB. kinda wish it was aRGB but what can ya do.

**Comment by AndrewBabbitt97** [comment]
If you have another free RGB header could you change the one your CPU fan is using and tell me if the RGB value seems to change from [3]

**Comment by Rylleyryelle** [comment]
been at work, sorry. it has 2 headers and tried both. both use [3] on the cpu fan for mine.

**Comment by AndrewBabbitt97** [comment]
Will be releasing a new version this weekend, logging will be included in this. I'll have you run this version when I release it.

**Comment by AndrewBabbitt97** [comment]
New release is out, please test this new release and let me know how things are in it:

https://github.com/AndrewBabbitt97/AuraConnect/releases/tag/1.0.1
