### ISSUE TITLE
light delay

### ISSUE THREAD

**Issue by etrigo1** [AndrewBabbitt97/AuraConnect#91]
I have a delay when changing colors. for example when making the color spectrum it just updates the color from second to second.
The problem is in the asus connector.
the asus connector is turned off and the color spectrum is performed normally. I have a thermaltake dospisitivo also synchronized with razer and it works well. the problem can only be with the connector.

**Comment by AndrewBabbitt97** [comment]
What ASUS devices do you have?

**Comment by AndrewBabbitt97** [comment]
Also performance metrics would be useful here: https://www.github.com/AndrewBabbitt97/AuraConnect/tree/master/docs%2FPerformanceMetrics.md

**Comment by etrigo1** [comment]
Hi
I will activate this to see if it works.
my devices are the motherboard and the RAMS only. The sdk is the most recent, I use the asus aura.

**Comment by etrigo1** [comment]
[AuraConnect - Cópia.log](https://github.com/AndrewBabbitt97/AuraConnect/files/5437714/AuraConnect.-.Copia.log)

**Comment by etrigo1** [comment]
[video-1603702279.zip](https://github.com/AndrewBabbitt97/AuraConnect/files/5437762/video-1603702279.zip)

**Comment by AndrewBabbitt97** [comment]
What lighting mode are you in? AuraConnect looks to be working correctly. How does it act when doing spectrum cycling?

**Comment by etrigo1** [comment]
it doesn't matter what mode I put on the Razer Chroma. there is always this delay in the colors. this happened recently, first it worked. I don't know if it was a razer update if not. But if you disable the connector and control the colors through your own aura, there is no problem.

**Comment by AndrewBabbitt97** [comment]
Mode actually does matter for me to diagnose issues.

Again, If you could show me how it acts when using spectrum cycling that would be very useful.

**Comment by etrigo1** [comment]
I put it in spectrum mode a little faster to make it easier to detect the problem. more slowly the same thing happens.
[video-1603710452.zip](https://github.com/AndrewBabbitt97/AuraConnect/files/5438397/video-1603710452.zip)

**Comment by Thopher99** [comment]
I'm experiencing the same issue.
Devices: ASUS ROG B550-E Strix, G.skill Trident z RGB *4
Armoury Crate version: 3.2.4.0

It just keeps stuttering regardless what lighting mode it runs, this even happening during the transition of two lighting modes.

Here are the video and log file.
[20201116_auraconnect_issue.zip](https://github.com/AndrewBabbitt97/AuraConnect/files/5543067/20201116_auraconnect_issue.zip)

Thank you.

**Comment by VANIRRA** [comment]
Can confirm the same thing
ASUS ROG STRIX X570-E, 2x G.skill Triden Z RGB 8GB, can really see the delay inside my Lian-Li PC-O11 Razer Edition. The case syncs perfectly fine with other peripherals(keyboard, mouse, etc) while the MB, CPU Cooler(although it's probably to blame Cooler Master/AMD for), and RAM are out of sync. I think it's the problem with the Razer software rather than this program tho because the CPU cooler is out of sync too but the RGB runs in different program and the sync itself

**Comment by aeroweasel** [comment]
I got the same thing

Hardware: ASUS ROG STRIX X570-E BIOS 2802, 4x memory modules (XPG D60G RGB), 2 Deepcool ARGB strips, 1 ARGB cooler (Aerocool Cylon 4), 1 RGB ASUS Strix 1080Ti.

Software:
+ Windows 10 20H2 19042.630
+ Armoury Crate 3.2.4.0
---------------------------------------------------
Armoury Crate UWP App      3.2.4.0     
ROG Live Service           1.1.10.0    
AURA Service (Lighting Service)  3.04.24     
Armoury Crate lite service  3.2.4       
ASUS AIOFan HAL            1.1.15      
ASUS AURA Extension Card HAL  1.0.24      
ASUS AURA Motherboard HAL  1.0.69.0    
ASUS AURA Odd Component    1.0.8       
ASUS Keyboard HAL          1.0.50      
ASUS MB Peripheral Products  1.0.32      
ASUS Mouse HAL             1.0.53      
ASUS MousePad HAL          1.0.1.2     
AacAudioHal                1.02.12     
AacDispaly                 1.1.25      
AacVGA                     0.0.3.0     
CosairDram                 1.0.13      
KingstonDram               1.0.28      
AURA DRAM Component        1.0.54      
ENE RGB HAL                1.1.28.0    
ENE_DRAM_RGB_AURA42        1.00.02     
ENE_EHD_ASM_HAL            1.00.05     
ENE_EHD_M2_HAL             1.00.04     
ENE_EHD_SSS_HAL            1.0.2.0     
GALAX GAMER RGB            1.00.02     
PHISON HAL                 1.0.6.0     
WD_BLACK AN1500            1.0.12.0    
---------------------------------------------------
+ Synapse 3.5.1130.111812
+ AuraConnect 1.1.0

With Synapse 3 closed Armoury Crate works normal.

I also tried Synapse with TT RGB Plus 1.3.8 and 1.3.9 Beta and the lighting is working and syncing at normal speed.

**Comment by NiwakaAlpaka** [comment]
[AuraConnect.txt.log](https://github.com/AndrewBabbitt97/AuraConnect/files/5775338/AuraConnect.txt.log)

I seem to be in the same boat. Lights on both my addressable strips and two sticks G.Skill Trident Z Royal become very choppy when applying effects from Razer Synapse. They work normally from the Aura app.

- AuraConnect 1.1.0
- Razer Synapse 3.5.1215.121019
- Aura Sync 1.07.79_V2.2.

**Comment by AndrewBabbitt97** [comment]
AuraConnect has been archived, please move onto the replacement ChromaControl: https://github.com/ChromaControl/ChromaControl
