### ISSUE TITLE
corrupt install

### ISSUE THREAD

**Issue by JTechHound** [AndrewBabbitt97/AuraConnect#92]
I get a corrupt install file error every time I try to install. Ive downloaded multiple times and same thing each time.
![Screenshot (13)](https://user-images.githubusercontent.com/73715868/97743643-58262200-1abc-11eb-8a8e-466f18ee1d5e.png)

**Comment by AndrewBabbitt97** [comment]
Could be antivirus or some other program on your PC causing this issue. The installer is known good and working, I test all installers and updates before I release them.

This is an Inno Setup installer. Inno Setup extracts files to a temporary directory during install, I have seen antivirus software see this as malicious (usually endpoint AV in corporate networks) and block it. Could be many things. First make sure the installer you downloaded isn't corrupted. You can also try to install in windows safe mode to see if you can do it there. 

Here's the hash on the latest release so you can compare:

Name: AuraConnectSetup.exe
Size: 11784246 bytes (11 MiB)
SHA256: E1A2344F9E82E168679FCC85EEBDE46519F98C645B2DD49ECBF0CD07D786BE9B

**Comment by AndrewBabbitt97** [comment]
AuraConnect has been archived, please move onto the replacement ChromaControl: https://github.com/ChromaControl/ChromaControl
