### ISSUE TITLE
Lighting does not turn off when display turns off

### ISSUE THREAD

**Issue by JakeThe3rdSnake** [AndrewBabbitt97/AuraConnect#93]
As is in the title, when the checkbox to switch off lighting when display is turned off, the lighting is not turned off, but instead it is paused until the display is woken back up. 
![image](https://user-images.githubusercontent.com/74017444/98280892-0ffa7a00-1f6a-11eb-8edb-220d2e367747.png)

**Comment by Electronic87** [comment]
I have the same issue. Any help getting this to work would be appreciated.

**Comment by kats1123** [comment]
Bump, same issue

**Comment by bigbutler** [comment]
that's never worked for me Auraconnect.
Use a RAZER ARGB hub an no probs for Sleep RGB.

**Comment by AnthonyMaiorani** [comment]
Any updates or workarounds for this issue yet?

**Comment by AndrewBabbitt97** [comment]
Priorities have been around moving to MSIX and deprecating this project in favor of [ChromaControl](https://github.com/ChromaControl/ChromaControl)

This will be added to my backlog for the project to investigate once stable release is out (works been busy right now so taking longer to get around to this). Gigabyte and SteelSeries device support is also planned. Right now I'm focused on critical bugs, after the project website, discord server, and other aspects are complete I will look at implementing this. It's more of a feature than a bug.

**Comment by AnthonyMaiorani** [comment]
Interesting note about the checkbox. I just tested the official MSI Mystic Light Chroma integration and it has the same issue, just freezing at the last color sent like AuraConnect does. So it definitely seems to be on Razer's side, my bad for jumping to conclusions. 

I hope you can figure this out though, definitely excited for SteelSeries support in ChromaControl too!

**Comment by AndrewBabbitt97** [comment]
I will probably have to reach out to the Synapse team to get more details on this, fortunately since starting this projects I have a lot more connections to the Chroma team to help address these kind of issues.

**Comment by AndrewBabbitt97** [comment]
AuraConnect has been archived, please move onto the replacement ChromaControl: https://github.com/ChromaControl/ChromaControl
