### ISSUE TITLE
Aura status "Unreachable"

### ISSUE THREAD

**Issue by Aptycs** [AndrewBabbitt97/AuraConnect#94]
Sometimes the Aura icon in Synapse Studio says "Unreachable" even though the Asus Armoury software is open and Aura active

**Comment by AndrewBabbitt97** [comment]
Only time I have ever seen unreachable is due to antivirus or anti cheat software, both are known to cause this.

Aside from this, logs from C:\ProgramData\AuraConnect\logs would be useful to confirm if this is the case.

**Comment by Aptycs** [comment]
Thank you!

**Comment by Calzo01** [comment]
Hey, i have had the same issue. I don't know how to resolve it. Suggestions?

**Comment by elcojone** [comment]
same issues here, AuraConnect is down (in Task Manager) after a couple of minutes. And even if I restart manually it won't sync in Razer Studio. And after a certain time is down again. Btw there is no logs-folder in my AuraConnect-folder
In Armoury Crate everything works fine.

**Comment by Calzo01** [comment]
Despite elcojone, my AuraConnect is running in task manager, but it doesn't sync all my Asus devices (it say "unreachable" in synapse). In the logs there is no information, also i don't have an antivirus running on this pc neither an anti cheat software.

**Comment by Calzo01** [comment]
> Only time I have ever seen unreachable is due to antivirus or anti cheat software, both are known to cause this.
> 
> Aside from this, logs from C:\ProgramData\AuraConnect\logs would be useful to confirm if this is the case.

Any suggestions for this problem?

**Comment by AndrewBabbitt97** [comment]
Try running the software manually from it's install directory and get a screenshot of the console window.

**Comment by AndrewBabbitt97** [comment]
AuraConnect has been archived, please move onto the replacement ChromaControl: https://github.com/ChromaControl/ChromaControl
