### ISSUE TITLE
Not showing up on Synapse at all.

### ISSUE THREAD

**Issue by Kahnsie** [AndrewBabbitt97/AuraConnect#95]
No clue why but it won't show with Synapse for some strange reason. Anyone else having this issue?

**Comment by AndrewBabbitt97** [comment]
This would usually indicate a startup issue. Most common startup issue I have seen is AURA/Armory Crate failing to register it's COM components correctly.

Is the AuraConnect service running? If not try to manually run AuraComnect.exe from the install directory.

**Comment by Kahnsie** [comment]
> This would usually indicate a startup issue. Most common startup issue I have seen is AURA/Armory Crate failing to register it's COM components correctly.
> 
> Is the AuraConnect service running? If not try to manually run AuraConnect.exe from the install directory.

Yes I have made sure its running. I've reinstalled twice too

**Comment by kyrk55** [comment]
Same here.
When i try manually run AuraConnect.exe i have this error:
![](https://user-images.githubusercontent.com/48693918/100298568-be09aa80-2f91-11eb-8ee1-46ef276df641.png)

**Comment by AndrewBabbitt97** [comment]
This means Aura/Armory Crate didn't register it's COM classes correctly. This is an issue with your Aura/Armory Crate install.

**Comment by Wefushi** [comment]
Same issue here. Anyone able to find a solution?

**Comment by AndrewBabbitt97** [comment]
> Same issue here. Anyone able to find a solution?

Reinstall Aura/Armory Crate. Install all HAL/Driver updates in Armory Crate. Make sure windows is on latest version (2004/2009).

**Comment by Wefushi** [comment]
> > Same issue here. Anyone able to find a solution?
> 
> Reinstall Aura/Armory Crate. Install all HAL/Driver updates in Armory Crate. Make sure windows is on latest version (2004/2009).

Did a clean install. Everything is up to date. Everything is running on services. Yet it does not appear on Razer Synapse.

I stopped the service AuraConnect manually and tried to start with the .exe on the installation folder. It gets stuck (image). Anti-virus is also turned off and i started the .exe with admin option.

![1](https://user-images.githubusercontent.com/75175308/100548944-e2060e00-3267-11eb-8ada-93905ca33e10.png)

No idea what is happening. Can you help me?

Thanks.

**Comment by aleksandarmanov** [comment]
> > > Same issue here. Anyone able to find a solution?
> > 
> > 
> > Reinstall Aura/Armory Crate. Install all HAL/Driver updates in Armory Crate. Make sure windows is on latest version (2004/2009).
> 
> Did a clean install. Everything is up to date. Everything is running on services. Yet it does not appear on Razer Synapse.
> 
> I stopped the service AuraConnect manually and tried to start with the .exe on the installation folder. It gets stuck (image). Anti-virus is also turned off and i started the .exe with admin option.
> 
> ![1](https://user-images.githubusercontent.com/75175308/100548944-e2060e00-3267-11eb-8ada-93905ca33e10.png)
> 
> No idea what is happening. Can you help me?
> 
> Thanks.
> 
> Edit: My bad i dont have the atkexComSvc service and i am on a laptop so ir doesnt work. Thanks and sorry to brother.

Hello, 

I have the exact same problem so I was wondering If you fixed it somehow? I'm using laptop too and every step was similar.

Thank you

**Comment by AndrewBabbitt97** [comment]
> > > > Same issue here. Anyone able to find a solution?
> > > 
> > > 
> > > Reinstall Aura/Armory Crate. Install all HAL/Driver updates in Armory Crate. Make sure windows is on latest version (2004/2009).
> > 
> > Did a clean install. Everything is up to date. Everything is running on services. Yet it does not appear on Razer Synapse.
> > 
> > I stopped the service AuraConnect manually and tried to start with the .exe on the installation folder. It gets stuck (image). Anti-virus is also turned off and i started the .exe with admin option.
> > 
> > ![1](https://user-images.githubusercontent.com/75175308/100548944-e2060e00-3267-11eb-8ada-93905ca33e10.png)
> > 
> > No idea what is happening. Can you help me?
> > 
> > Thanks.
> > 
> > Edit: My bad i dont have the atkexComSvc service and i am on a laptop so ir doesnt work. Thanks and sorry to brother.
> 
> Hello, 
> 
> I have the exact same problem so I was wondering If you fixed it somehow? I'm using laptop too and every step was similar.
> 
> Thank you

Laptops aren't supported. Even if they were, it wouldn't be a great experience due to limitations of Chroma Connect. In general keyboards and laptops aren't supported. Main intent is for desktop motherboards and RGB headers, other devices may work but not supported.

**Comment by aleksandarmanov** [comment]
> > > > > Same issue here. Anyone able to find a solution?
> > > > 
> > > > 
> > > > Reinstall Aura/Armory Crate. Install all HAL/Driver updates in Armory Crate. Make sure windows is on latest version (2004/2009).
> > > 
> > > 
> > > Did a clean install. Everything is up to date. Everything is running on services. Yet it does not appear on Razer Synapse.
> > > I stopped the service AuraConnect manually and tried to start with the .exe on the installation folder. It gets stuck (image). Anti-virus is also turned off and i started the .exe with admin option.
> > > ![1](https://user-images.githubusercontent.com/75175308/100548944-e2060e00-3267-11eb-8ada-93905ca33e10.png)
> > > No idea what is happening. Can you help me?
> > > Thanks.
> > > Edit: My bad i dont have the atkexComSvc service and i am on a laptop so ir doesnt work. Thanks and sorry to brother.
> > 
> > 
> > Hello,
> > I have the exact same problem so I was wondering If you fixed it somehow? I'm using laptop too and every step was similar.
> > Thank you
> 
> Laptops aren't supported. Even if they were, it wouldn't be a great experience due to limitations of Chroma Connect. In general keyboards and laptops aren't supported. Main intent is for desktop motherboards and RGB headers, other devices may work but not supported.

Thank you for fast feedback!
