### ISSUE TITLE
AuraConnect hangs

### ISSUE THREAD

**Issue by Bilalali95** [AndrewBabbitt97/AuraConnect#98]
I understand that there is supposed to be a minor delay between Razer and Asus however, it seems like the software hangs at times with the motherboard (ASUS TUF GAMING X570-PLUS (Wi-Fi)) and fans at a different colour than the mouse and keyboard.

On Synapse the only lighting effect I have tried is the spectrum cycle at different speeds.

I have uninstalled and installed both Armoury Crate and AuraConnect several times to test issues with Armoury Crate. What I found is that if you download Armoury Crate and AuraConnect without restarting the computer then the lights sync up with no delays or hangs. Once the PC is restarted that’s when the LEDs start to hang again right after the restart then aura connect starts 
to hang again.

I have provided the log and a video.
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/5605239/AuraConnect.log)
[2020-11-26 at 6.07.07 PM.zip](https://github.com/AndrewBabbitt97/AuraConnect/files/5605256/2020-11-26.at.6.07.07.PM.zip)

**Comment by AndrewBabbitt97** [comment]
There will always be a freeze at startup for a bit, this is part of my code. This is intentional.

Looking at your logs, everything on the Synapse/AuraConnect side is working correctly. Unfortunately this means there's nothing I can really do to help if you are having issues. The issue lies in the Aura/ASUS side of things.

**Comment by Bilalali95** [comment]
When I reinstall Armoury Crate without restarting my pc it works perfectly fine. Is there a way to make it work without Armoury Crate or Aura sync?

**Comment by AndrewBabbitt97** [comment]
No it's a hard requirement, my software uses Aura/Armory Crate (which provides the Aura SDK) in order to control Aura devices. I can't control Aura devices without it.

**Comment by Bilalali95** [comment]
Oh ok, I get it, then its probably from my PC, if I decide to do a clean reinstall of windows to see if that fixes anything ill let you know. However, the software itself is very nice when it ran smoothly and I really appreciate the quick responses.

**Comment by Bilalali95** [comment]
I fixed the issue somewhat by changing the priority level of all Armoury Crate processes or under details (I changed them all to realtime).
